defmodule GridCodec.RustFixtureTest do
  use ExUnit.Case, async: true

  @fixtures Path.expand("fixtures", __DIR__)

  test "header fixture is generated by the Elixir wire contract" do
    expected =
      GridCodec.Header.encode(block_length: 32, template_id: 1, schema_id: 100, version: 2)

    assert fixture!("header.hex") == expected
  end

  test "primitive fixture uses GridCodec little-endian and var-data layout" do
    expected = <<42::little-32, -7::little-signed-64, 1::8, 4::8, "grid"::binary>>
    assert fixture!("primitives.hex") == expected
  end

  defp fixture!(name) do
    @fixtures
    |> Path.join(name)
    |> File.read!()
    |> String.trim()
    |> Base.decode16!(case: :mixed)
  end
end
