defmodule GridCodec.Registry do
  @moduledoc """
  Registry for GridCodec modules - fallback implementation.

  This module provides runtime discovery and dispatch when the consolidated
  registry (generated by the `:grid_codec` Mix compiler) is not available.

  In production releases, this module is replaced by an optimized version
  with pattern-match dispatch generated at compile time.

  ## Usage

  The top-level `GridCodec` module delegates to this registry:

      # Encode a struct
      {:ok, binary} = GridCodec.encode(my_struct)

      # Decode using header dispatch
      {:ok, decoded_struct} = GridCodec.decode(binary)

  ## Direct API

      # Look up codec by schema_id and template_id
      {:ok, MyApp.Order} = GridCodec.Registry.lookup(100, 1)

      # List all registered codecs
      GridCodec.Registry.list_codecs()
      #=> [MyApp.Order, MyApp.Trade, ...]

  ## Implementation

  This fallback uses runtime module scanning to discover codecs.
  For production, use the `:grid_codec` Mix compiler to generate
  an optimized registry with pattern-match dispatch.
  """

  @doc """
  Eagerly loads all GridCodec modules from beam files on the code path.

  The BEAM VM loads modules lazily — codec modules may not be in
  `:code.all_loaded()` until something references them. Call this at
  application startup to ensure `list_codecs/0` and `lookup/2` can
  find all codecs without the consolidated registry.

  ## Example

      # In your Application.start/2:
      GridCodec.Registry.ensure_all_loaded()
  """
  @spec ensure_all_loaded() :: :ok
  def ensure_all_loaded do
    :code.get_path()
    |> Enum.flat_map(fn dir ->
      Path.wildcard(Path.join(List.to_string(dir), "*.beam"))
    end)
    |> Enum.each(fn beam ->
      mod = beam |> Path.basename(".beam") |> String.to_atom()
      Code.ensure_loaded(mod)
    end)

    clear_cache()
    :ok
  end

  @doc """
  Lists all GridCodec modules currently loaded in the system.

  This scans all loaded modules and checks if they implement GridCodec
  by looking for the `__schema__/0` and `encode/1` functions.

  Note: BEAM loads modules lazily. Call `ensure_all_loaded/0` at startup
  or use the `:grid_codec` Mix compiler for reliable discovery.

  ## Example

      iex> GridCodec.Registry.list_codecs()
      [MyApp.OrderEvent, MyApp.TradeEvent]

  ## Options

  - `:filter` - A function to filter codecs, receives module name
  - `:namespace` - Only return codecs under this namespace (e.g., `MyApp.Events`)
  """
  @spec list_codecs(keyword()) :: [module()]
  def list_codecs(opts \\ []) do
    filter_fn = Keyword.get(opts, :filter, fn _ -> true end)
    namespace = Keyword.get(opts, :namespace)

    :code.all_loaded()
    |> Enum.map(fn {mod, _} -> mod end)
    |> Enum.filter(&is_gridcodec?/1)
    |> Enum.filter(fn mod ->
      passes_namespace?(mod, namespace) and filter_fn.(mod)
    end)
    |> Enum.sort()
  end

  @doc """
  Returns detailed information about a codec module.

  ## Example

      iex> GridCodec.Registry.codec_info(MyApp.OrderEvent)
      %{
        module: MyApp.OrderEvent,
        fields: [:id, :price, :quantity],
        fixed_fields: [:id, :price, :quantity],
        var_fields: [],
        block_length: 20,
        version: 1,
        endian: :little
      }

  Returns `nil` if the module is not a valid GridCodec.
  """
  @spec codec_info(module()) :: map() | nil
  def codec_info(module) when is_atom(module) do
    if is_gridcodec?(module) do
      schema = module.__schema__()

      %{
        module: module,
        fields: module.__fields__(),
        fixed_fields: schema.fixed_fields,
        var_fields: schema.var_fields,
        groups: length(schema.groups),
        block_length: schema.block_length,
        version: schema.version,
        endian: schema.endian
      }
    else
      nil
    end
  end

  @doc """
  Finds all codecs that have a specific field.

  ## Example

      iex> GridCodec.Registry.find_by_field(:order_id)
      [MyApp.OrderEvent, MyApp.CancelEvent]
  """
  @spec find_by_field(atom(), keyword()) :: [module()]
  def find_by_field(field_name, opts \\ []) when is_atom(field_name) do
    list_codecs(opts)
    |> Enum.filter(fn mod ->
      field_name in mod.__fields__()
    end)
  end

  @doc """
  Returns all unique field names across all codecs.

  ## Example

      iex> GridCodec.Registry.all_fields()
      [:id, :order_id, :price, :quantity, :side, :timestamp]
  """
  @spec all_fields(keyword()) :: [atom()]
  def all_fields(opts \\ []) do
    list_codecs(opts)
    |> Enum.flat_map(fn mod -> mod.__fields__() end)
    |> Enum.uniq()
    |> Enum.sort()
  end

  @doc """
  Generates a summary report of all codecs in the system.

  ## Example

      iex> GridCodec.Registry.summary()
      %{
        total_codecs: 5,
        total_fields: 23,
        total_block_bytes: 156,
        codecs: [
          %{module: MyApp.OrderEvent, fields: 7, block_length: 46},
          ...
        ]
      }
  """
  @spec summary(keyword()) :: map()
  def summary(opts \\ []) do
    codecs = list_codecs(opts)

    codec_summaries =
      Enum.map(codecs, fn mod ->
        info = codec_info(mod)

        %{
          module: mod,
          fields: length(info.fields),
          block_length: info.block_length,
          has_groups: info.groups > 0,
          has_var_fields: info.var_fields != []
        }
      end)

    %{
      total_codecs: length(codecs),
      total_fields: codec_summaries |> Enum.map(& &1.fields) |> Enum.sum(),
      total_block_bytes: codec_summaries |> Enum.map(& &1.block_length) |> Enum.sum(),
      codecs: codec_summaries
    }
  end

  @doc """
  Validates that a module is a valid GridCodec.

  Returns `{:ok, info}` or `{:error, reason}`.

  ## Example

      iex> GridCodec.Registry.validate(MyApp.OrderEvent)
      {:ok, %{module: MyApp.OrderEvent, fields: [:id, :price], ...}}

      iex> GridCodec.Registry.validate(String)
      {:error, :not_a_gridcodec}
  """
  @spec validate(module()) :: {:ok, map()} | {:error, atom()}
  def validate(module) when is_atom(module) do
    cond do
      not Code.ensure_loaded?(module) ->
        {:error, :module_not_found}

      not is_gridcodec?(module) ->
        {:error, :not_a_gridcodec}

      true ->
        {:ok, codec_info(module)}
    end
  end

  # ============================================================================
  # Dispatch API (for top-level GridCodec functions)
  # ============================================================================

  @doc """
  Look up a codec module by schema_id and template_id.

  ## Example

      {:ok, MyApp.Order} = GridCodec.Registry.lookup(100, 1)
      {:error, :unknown_codec} = GridCodec.Registry.lookup(999, 999)
  """
  @spec lookup(non_neg_integer(), non_neg_integer()) :: {:ok, module()} | {:error, :unknown_codec}
  def lookup(schema_id, template_id) do
    case find_struct_codec(schema_id, template_id) do
      nil -> {:error, :unknown_codec}
      module -> {:ok, module}
    end
  end

  @doc """
  Look up a codec module by its type name.

  The type name is set via the `:name` option on `use GridCodec.Struct`,
  or defaults to the last segment of the module name.

  Useful for EventStore integration where events are stored with a short
  type string instead of the full Elixir module name.

  ## Example

      {:ok, MyApp.Events.OrderSubmitted} = GridCodec.Registry.lookup_by_type("OrderSubmitted")
      {:error, :unknown_type} = GridCodec.Registry.lookup_by_type("NonExistent")
  """
  @spec lookup_by_type(String.t()) :: {:ok, module()} | {:error, :unknown_type}
  def lookup_by_type(type_name) when is_binary(type_name) do
    table = get_or_build_type_lookup_table()

    case Map.get(table, type_name) do
      nil ->
        refreshed = build_type_lookup_table()
        :persistent_term.put({__MODULE__, :type_lookup_table}, refreshed)

        case Map.get(refreshed, type_name) do
          nil -> {:error, :unknown_type}
          module -> {:ok, module}
        end

      module ->
        {:ok, module}
    end
  end

  @doc """
  Looks up an enum module by its short name (last module segment).

  Searches all loaded modules that implement the `GridCodec.Types.Enum`
  behaviour (export `values/0` and `encoding/0`).

  Used by the `grid_file:` compiler path to auto-resolve `.grid` type
  names to Elixir modules.

  ## Examples

      {:ok, MyApp.Types.OrderSide} = GridCodec.Registry.lookup_enum_by_name("OrderSide")
      :error = GridCodec.Registry.lookup_enum_by_name("NonExistent")
  """
  @spec lookup_enum_by_name(String.t()) :: {:ok, module()} | :error
  def lookup_enum_by_name(name) when is_binary(name) do
    result =
      :code.all_loaded()
      |> Enum.find_value(fn {mod, _} ->
        if is_enum_module?(mod) and short_module_name(mod) == name do
          mod
        end
      end)

    case result do
      nil -> :error
      mod -> {:ok, mod}
    end
  end

  defp is_enum_module?(mod) do
    Code.ensure_loaded?(mod) and
      function_exported?(mod, :values, 0) and
      function_exported?(mod, :encoding, 0)
  end

  @doc """
  Looks up a custom type module (PrefixedId, CharArray, Bitset) by its short name.

  Searches all loaded modules that export one of the meta functions:
  `__prefixed_id_meta__/0`, `__char_array_meta__/0`, or `__bitset_meta__/0`.

  ## Examples

      {:ok, MyApp.Types.UserId} = GridCodec.Registry.lookup_custom_type_by_name("UserId")
      :error = GridCodec.Registry.lookup_custom_type_by_name("NonExistent")
  """
  @spec lookup_custom_type_by_name(String.t()) :: {:ok, module()} | :error
  def lookup_custom_type_by_name(name) when is_binary(name) do
    result =
      :code.all_loaded()
      |> Enum.find_value(fn {mod, _} ->
        if is_custom_type_module?(mod) and short_module_name(mod) == name do
          mod
        end
      end)

    case result do
      nil -> :error
      mod -> {:ok, mod}
    end
  end

  defp is_custom_type_module?(mod) do
    Code.ensure_loaded?(mod) and
      (function_exported?(mod, :__prefixed_id_meta__, 0) or
         function_exported?(mod, :__char_array_meta__, 0) or
         function_exported?(mod, :__bitset_meta__, 0))
  end

  defp short_module_name(mod) do
    mod |> Module.split() |> List.last()
  end

  @doc """
  Encode a struct to binary.

  The struct must be a registered GridCodec struct.
  By default includes header for dispatch via `GridCodec.decode/1`.

  ## Options

  - `:header` - Include header (default: `true`)

  ## Example

      order = %MyApp.Order{id: <<1::128>>, price: 100}
      {:ok, binary} = GridCodec.Registry.encode(order)
      {:ok, payload} = GridCodec.Registry.encode(order, header: false)
  """
  @spec encode(struct(), keyword()) ::
          {:ok, binary()} | {:error, GridCodec.ValidationError.t()}
  def encode(struct, opts \\ [])

  def encode(%{__struct__: module} = struct, opts) do
    if is_gridcodec_struct?(module) do
      module.encode(struct, opts)
    else
      {:error,
       GridCodec.ValidationError.cast_error(
         module,
         :unknown,
         :encode,
         struct,
         "not a registered GridCodec struct"
       )}
    end
  end

  @doc """
  Decode a binary, dispatching to the correct codec.

  By default expects an 8-byte GridCodec header for module dispatch.

  ## Options

  - `:header` - Expect header (default: `true`)
  - `:module` - Required when `header: false` to specify the codec module

  ## Examples

      # With header (default)
      {:ok, %MyApp.Order{}} = GridCodec.Registry.decode(binary)

      # Without header - must specify module
      {:ok, %MyApp.Order{}} = GridCodec.Registry.decode(payload, header: false, module: MyApp.Order)
  """
  @spec decode(binary(), keyword()) :: {:ok, struct()} | {:error, term()}
  def decode(binary, opts \\ [])

  def decode(binary, []) when is_binary(binary) do
    case GridCodec.Header.decode(binary) do
      {:ok, header, payload} ->
        case find_struct_codec(header.schema_id, header.template_id) do
          nil ->
            {:error, :unknown_codec}

          module ->
            module.decode(payload, header: false)
        end

      {:error, _} = error ->
        error
    end
  end

  def decode(binary, opts) when is_binary(binary) do
    if Keyword.get(opts, :header, true) do
      case GridCodec.Header.decode(binary) do
        {:ok, header, payload} ->
          case find_struct_codec(header.schema_id, header.template_id) do
            nil ->
              {:error, :unknown_codec}

            module ->
              module.decode(payload, header: false)
          end

        {:error, _} = error ->
          error
      end
    else
      case Keyword.fetch(opts, :module) do
        {:ok, module} ->
          module.decode(binary, header: false)

        :error ->
          {:error, :module_required_without_header}
      end
    end
  end

  @doc """
  Returns whether this is a consolidated registry.

  The consolidated registry is generated by the `:grid_codec` Mix compiler
  and provides optimized pattern-match dispatch.

  ## Example

      iex> GridCodec.Registry.consolidated?()
      false  # fallback registry (runtime discovery)
  """
  @spec consolidated?() :: boolean()
  def consolidated?, do: false

  # ============================================================================
  # Private Helpers
  # ============================================================================

  defp is_gridcodec?(module) do
    Code.ensure_loaded?(module) and
      function_exported?(module, :__schema__, 0) and
      function_exported?(module, :__fields__, 0) and
      function_exported?(module, :encode, 1) and
      function_exported?(module, :decode, 1)
  end

  defp is_gridcodec_struct?(module) do
    Code.ensure_loaded?(module) and
      function_exported?(module, :__gridcodec_struct__?, 0) and
      function_exported?(module, :__template_id__, 0) and
      function_exported?(module, :__schema_id__, 0)
  end

  # Use persistent_term to cache the lookup table across all processes
  @doc """
  Clears the codec lookup table cache.

  This forces the registry to rebuild the lookup table on the next decode
  operation. Useful in tests when new codecs are defined dynamically.

  ## Example

      GridCodec.Registry.clear_cache()
  """
  @spec clear_cache() :: :ok
  def clear_cache do
    :persistent_term.erase({__MODULE__, :codec_lookup_table})
    :persistent_term.erase({__MODULE__, :type_lookup_table})
    :ok
  rescue
    ArgumentError -> :ok
  end

  # This avoids calling :code.all_loaded() on every decode operation
  defp find_struct_codec(schema_id, template_id) do
    table = get_or_build_lookup_table()
    key = {schema_id, template_id}

    case Map.get(table, key) do
      nil ->
        # Fallback refresh for dynamic module loading in dev/test.
        refreshed = build_lookup_table()
        :persistent_term.put({__MODULE__, :codec_lookup_table}, refreshed)
        Map.get(refreshed, key)

      module ->
        module
    end
  end

  defp get_or_build_lookup_table do
    case :persistent_term.get({__MODULE__, :codec_lookup_table}, :not_found) do
      :not_found ->
        # Build lookup table once: {schema_id, template_id} => module
        # This is expensive but only happens once
        table = build_lookup_table()

        :persistent_term.put({__MODULE__, :codec_lookup_table}, table)
        table

      table ->
        table
    end
  end

  defp build_lookup_table do
    :code.all_loaded()
    |> Enum.reduce(%{}, fn {mod, _}, acc ->
      if is_gridcodec_struct?(mod) do
        try do
          schema_id = mod.__schema_id__()
          template_id = mod.__template_id__()
          Map.put(acc, {schema_id, template_id}, mod)
        rescue
          _ -> acc
        end
      else
        acc
      end
    end)
  end

  defp get_or_build_type_lookup_table do
    case :persistent_term.get({__MODULE__, :type_lookup_table}, :not_found) do
      :not_found ->
        table = build_type_lookup_table()
        :persistent_term.put({__MODULE__, :type_lookup_table}, table)
        table

      table ->
        table
    end
  end

  defp build_type_lookup_table do
    :code.all_loaded()
    |> Enum.reduce(%{}, fn {mod, _}, acc ->
      if is_gridcodec_struct?(mod) and function_exported?(mod, :__type__, 0) do
        try do
          type = mod.__type__()

          case Map.get(acc, type) do
            nil ->
              Map.put(acc, type, mod)

            existing ->
              require Logger

              Logger.warning(
                "GridCodec type name collision: #{inspect(type)} is claimed by " <>
                  "both #{inspect(existing)} and #{inspect(mod)}. " <>
                  "Use the :name option to assign unique type names."
              )

              acc
          end
        rescue
          _ -> acc
        end
      else
        acc
      end
    end)
  end

  defp passes_namespace?(_mod, nil), do: true

  defp passes_namespace?(mod, namespace) when is_atom(namespace) do
    mod_string = Atom.to_string(mod)
    namespace_string = Atom.to_string(namespace)
    String.starts_with?(mod_string, namespace_string)
  end
end
