defmodule GridCodec.SQL do
  @moduledoc """
  Generates PostgreSQL functions for decoding GridCodec binaries stored as `bytea`.

  Produces pure SQL functions that extract typed fields from GridCodec binaries
  at their compile-time-known offsets. No PostgreSQL extension required.

  ## Usage

      # Generate SQL for a single codec
      sql = GridCodec.SQL.generate(MyApp.Events.OrderSubmitted)

      # Generate SQL for all registered codecs
      sql = GridCodec.SQL.generate_all()

      # Write to file
      GridCodec.SQL.generate_all_to_file("priv/gridcodec_functions.sql")

  ## Generated Functions

  For each codec, generates:
  - `gridcodec.decode_<type_name>(bytea)` — full decode returning a row with typed columns
  - Enum lookup tables in `gridcodec_enums` schema

  Shared helper functions:
  - `gridcodec.read_header(bytea)` — parse the 8-byte header
  - `gridcodec.read_u8(bytea, int)`, `read_u16(...)`, etc. — type extractors
  - `gridcodec.read_decimal(bytea, int)` — mantissa/exponent → `numeric`
  - `gridcodec.read_timestamp_us(bytea, int)` — microseconds → `timestamptz`
  """

  @header_size 8

  @doc """
  Generates the shared SQL helper functions and schema setup.
  """
  def generate_helpers do
    """
    -- ============================================================
    -- GridCodec PostgreSQL Helpers
    -- Generated by GridCodec.SQL
    -- ============================================================

    CREATE SCHEMA IF NOT EXISTS gridcodec;
    CREATE SCHEMA IF NOT EXISTS gridcodec_enums;

    -- Header parser: 8 bytes → {block_length, template_id, schema_id, version}
    CREATE OR REPLACE FUNCTION gridcodec.read_header(data bytea)
    RETURNS TABLE (block_length int, template_id int, schema_id int, version int)
    AS $$
    SELECT
      get_byte(data, 0) + get_byte(data, 1) * 256,
      get_byte(data, 2) + get_byte(data, 3) * 256,
      get_byte(data, 4) + get_byte(data, 5) * 256,
      get_byte(data, 6) + get_byte(data, 7) * 256;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Unsigned integer readers (little-endian)
    CREATE OR REPLACE FUNCTION gridcodec.read_u8(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT get_byte(data, pos)::smallint;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u16(data bytea, pos int)
    RETURNS integer AS $$
      SELECT (get_byte(data, pos) + get_byte(data, pos + 1) * 256)::integer;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u32(data bytea, pos int)
    RETURNS bigint AS $$
      SELECT (get_byte(data, pos)::bigint
            + get_byte(data, pos + 1)::bigint * 256
            + get_byte(data, pos + 2)::bigint * 65536
            + get_byte(data, pos + 3)::bigint * 16777216);
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u64(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT (get_byte(data, pos)::numeric
            + get_byte(data, pos + 1)::numeric * 256
            + get_byte(data, pos + 2)::numeric * 65536
            + get_byte(data, pos + 3)::numeric * 16777216
            + get_byte(data, pos + 4)::numeric * 4294967296
            + get_byte(data, pos + 5)::numeric * 1099511627776
            + get_byte(data, pos + 6)::numeric * 281474976710656
            + get_byte(data, pos + 7)::numeric * 72057594037927936);
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Signed integer readers (little-endian, two's complement)
    CREATE OR REPLACE FUNCTION gridcodec.read_i8(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT CASE
        WHEN get_byte(data, pos) >= 128
        THEN (get_byte(data, pos) - 256)::smallint
        ELSE get_byte(data, pos)::smallint
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i16(data bytea, pos int)
    RETURNS integer AS $$
      SELECT CASE
        WHEN gridcodec.read_u16(data, pos) >= 32768
        THEN (gridcodec.read_u16(data, pos) - 65536)::integer
        ELSE gridcodec.read_u16(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i32(data bytea, pos int)
    RETURNS bigint AS $$
      SELECT CASE
        WHEN gridcodec.read_u32(data, pos) >= 2147483648
        THEN (gridcodec.read_u32(data, pos) - 4294967296)::bigint
        ELSE gridcodec.read_u32(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i64(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT CASE
        WHEN get_byte(data, pos + 7) >= 128
        THEN gridcodec.read_u64(data, pos) - 18446744073709551616::numeric
        ELSE gridcodec.read_u64(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- UUID reader: 16 bytes → uuid
    CREATE OR REPLACE FUNCTION gridcodec.read_uuid(data bytea, pos int)
    RETURNS uuid AS $$
      SELECT encode(substring(data FROM pos + 1 FOR 16), 'hex')::uuid;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- UUID null check (all zeros = null)
    CREATE OR REPLACE FUNCTION gridcodec.read_uuid_nullable(data bytea, pos int)
    RETURNS uuid AS $$
      SELECT CASE
        WHEN substring(data FROM pos + 1 FOR 16) = '\\x00000000000000000000000000000000'::bytea
        THEN NULL
        ELSE encode(substring(data FROM pos + 1 FOR 16), 'hex')::uuid
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Decimal reader: 8 bytes mantissa (i64 LE) + 1 byte exponent (i8) → numeric
    CREATE OR REPLACE FUNCTION gridcodec.read_decimal(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT CASE
        WHEN gridcodec.read_i64(data, pos) = -9223372036854775808::numeric
        THEN NULL
        ELSE gridcodec.read_i64(data, pos) * power(10, CASE
          WHEN get_byte(data, pos + 8) >= 128
          THEN get_byte(data, pos + 8) - 256
          ELSE get_byte(data, pos + 8)
        END)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Timestamp reader: i64 microseconds → timestamptz
    CREATE OR REPLACE FUNCTION gridcodec.read_timestamp_us(data bytea, pos int)
    RETURNS timestamptz AS $$
      SELECT CASE
        WHEN gridcodec.read_i64(data, pos) = 0
        THEN NULL
        ELSE to_timestamp(gridcodec.read_i64(data, pos) / 1000000.0)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- PrefixedId reader: 1 byte tag + 16 byte UUID → tag:uuid text
    -- Null: tag=0 and uuid=all-zeros
    CREATE OR REPLACE FUNCTION gridcodec.read_prefixed_id(data bytea, pos int)
    RETURNS text AS $$
      SELECT CASE
        WHEN get_byte(data, pos) = 0
         AND substring(data FROM pos + 2 FOR 16) = '\\x00000000000000000000000000000000'::bytea
        THEN NULL
        ELSE encode(substring(data FROM pos + 2 FOR 16), 'hex')::uuid::text
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_prefixed_id_tag(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT get_byte(data, pos)::smallint;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Bool reader: 0=false, 1=true, 255=null
    CREATE OR REPLACE FUNCTION gridcodec.read_bool(data bytea, pos int)
    RETURNS boolean AS $$
      SELECT CASE get_byte(data, pos)
        WHEN 0 THEN false
        WHEN 255 THEN NULL
        ELSE true
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- String16 reader: 2-byte LE length prefix + data
    CREATE OR REPLACE FUNCTION gridcodec.read_string16(data bytea, pos int)
    RETURNS text AS $$
      SELECT CASE gridcodec.read_u16(data, pos)
        WHEN 0 THEN NULL
        ELSE convert_from(
          substring(data FROM pos + 3 FOR gridcodec.read_u16(data, pos)),
          'UTF8'
        )
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;
    """
  end

  @doc """
  Generates SQL for a single codec module.
  """
  def generate(module) when is_atom(module) do
    schema = module.__schema__()
    type_name = module.__type__()
    field_specs = module.__field_specs__()
    fields = schema.fields
    block_length = schema.block_length

    fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")

    enum_tables = generate_enum_tables(fields)

    decode_fn =
      generate_decode_function(fn_name, type_name, module, fields, field_specs, block_length)

    enum_tables <> decode_fn
  end

  @doc """
  Generates SQL for all registered GridCodec codecs.

  Pass an explicit list of modules for reliable results in scripts,
  or call with no arguments to scan all loaded modules.

      GridCodec.SQL.generate_all()
      GridCodec.SQL.generate_all([MyApp.Events.OrderCreated, MyApp.Events.TradeFilled])
  """
  def generate_all(modules \\ nil) do
    codecs =
      case modules do
        nil ->
          :code.all_loaded()
          |> Enum.map(fn {mod, _} -> mod end)
          |> Enum.filter(&gridcodec_codec?/1)

        mods when is_list(mods) ->
          Enum.filter(mods, &gridcodec_codec?/1)
      end
      |> Enum.sort_by(& &1.__type__())

    helpers = generate_helpers()
    codec_sql = Enum.map_join(codecs, "\n", &generate/1)
    universal_decoder = generate_universal_decoder(codecs)

    helpers <> "\n" <> codec_sql <> "\n" <> universal_decoder
  end

  @doc """
  Generates SQL and writes it to a file.
  """
  def generate_all_to_file(path, modules \\ nil) do
    sql = generate_all(modules)
    File.write!(path, sql)
    {:ok, path}
  end

  defp gridcodec_codec?(mod) do
    Code.ensure_loaded?(mod) and
      function_exported?(mod, :__gridcodec_struct__?, 0) and
      function_exported?(mod, :__field_specs__, 0) and
      function_exported?(mod, :__type__, 0)
  end

  # ============================================================================
  # Private: Enum Table Generation
  # ============================================================================

  defp generate_enum_tables(fields) do
    fields
    |> Enum.filter(fn {_name, type, _opts} -> enum_type?(type) end)
    |> Enum.map(fn {_name, type, _opts} -> type end)
    |> Enum.uniq()
    |> Enum.map_join("\n", &generate_enum_table/1)
  end

  defp enum_type?(type) when is_atom(type) do
    case Code.ensure_compiled(type) do
      {:module, _} ->
        function_exported?(type, :to_atom, 1) and function_exported?(type, :to_integer, 1)

      _ ->
        false
    end
  end

  defp enum_type?({_type, _opts}), do: false
  defp enum_type?(_), do: false

  defp prefixed_id_type?(type) when is_atom(type) do
    case Code.ensure_compiled(type) do
      {:module, _} -> function_exported?(type, :__prefixed_id_meta__, 0)
      _ -> false
    end
  end

  defp prefixed_id_type?(_), do: false

  defp prefixed_id_prefix(type) do
    type.__prefixed_id_meta__().prefix
  end

  defp generate_enum_table(enum_module) do
    table_name = enum_table_name(enum_module)

    values =
      if function_exported?(enum_module, :values, 0) do
        enum_module.values()
      else
        []
      end

    if values == [] do
      ""
    else
      rows =
        Enum.map_join(values, ",\n  ", fn {atom, int} ->
          "(#{int}, '#{atom}')"
        end)

      """
      -- Enum: #{inspect(enum_module)}
      CREATE TABLE IF NOT EXISTS gridcodec_enums.#{table_name} (
        id smallint PRIMARY KEY,
        name text NOT NULL
      );
      TRUNCATE gridcodec_enums.#{table_name};
      INSERT INTO gridcodec_enums.#{table_name} (id, name) VALUES
        #{rows};

      """
    end
  end

  defp enum_table_name(module) do
    module
    |> Module.split()
    |> List.last()
    |> Macro.underscore()
  end

  # ============================================================================
  # Private: Decode Function Generation
  # ============================================================================

  defp generate_decode_function(fn_name, type_name, module, fields, field_specs, block_length) do
    fixed_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        case Map.get(field_specs, name) do
          {:variable, _} -> false
          {:group, _} -> false
          nil -> false
          _ -> true
        end
      end)

    var_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        match?({:variable, _}, Map.get(field_specs, name))
      end)

    columns =
      Enum.map(fixed_fields ++ var_fields, fn {name, type, _opts} ->
        {name, sql_column_type(type)}
      end)

    column_defs =
      Enum.map_join(columns, ",\n  ", fn {name, type} ->
        "\"#{name}\" #{type}"
      end)

    select_exprs =
      Enum.map(fixed_fields, fn {name, type, _opts} ->
        {type_mod, offset, _endian} = Map.fetch!(field_specs, name)
        sql_read_expr(name, type, type_mod, offset)
      end)

    # Variable-length fields are sequential: each starts after the previous one's
    # 2-byte length prefix + content. We track the cumulative offset in SQL.
    {var_select_exprs, _} =
      Enum.map_reduce(var_fields, nil, fn {name, type, _opts}, prev_offset_expr ->
        offset_expr =
          case prev_offset_expr do
            nil ->
              "#{@header_size + block_length}"

            prev ->
              "#{prev} + 2 + gridcodec.read_u16(data, #{prev})"
          end

        expr = sql_read_var_expr(name, type, offset_expr)
        {expr, offset_expr}
      end)

    all_exprs = Enum.map_join(select_exprs ++ var_select_exprs, ",\n  ", & &1)

    """
    -- Codec: #{inspect(module)}
    -- Type: "#{type_name}", block_length: #{block_length}
    CREATE OR REPLACE FUNCTION gridcodec.decode_#{fn_name}(data bytea)
    RETURNS TABLE (
      #{column_defs}
    ) AS $$
    SELECT
      #{all_exprs};
    $$ LANGUAGE sql IMMUTABLE STRICT;

    """
  end

  # ============================================================================
  # Private: Universal JSONB Decoder
  # ============================================================================

  defp generate_universal_decoder(codecs) do
    when_clauses =
      Enum.map_join(codecs, "\n    ", fn mod ->
        type_name = mod.__type__()
        fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")
        "WHEN type_name = '#{type_name}' THEN gridcodec.decode_#{fn_name}_json(data)"
      end)

    json_fns = Enum.map_join(codecs, "\n", &generate_json_function/1)

    json_fns <>
      """
      -- Universal decoder: returns any event as JSONB by type name
      --
      -- Usage:
      --   SELECT gridcodec.decode(event_type, data) FROM events;
      --   SELECT gridcodec.decode(event_type, data)->>'side' FROM events;
      --
      CREATE OR REPLACE FUNCTION gridcodec.decode(type_name text, data bytea)
      RETURNS jsonb AS $$
      SELECT CASE
        #{when_clauses}
        ELSE jsonb_build_object('_error', 'unknown type: ' || type_name)
      END;
      $$ LANGUAGE sql IMMUTABLE STRICT;

      """
  end

  defp generate_json_function(module) do
    schema = module.__schema__()
    type_name = module.__type__()
    field_specs = module.__field_specs__()
    fields = schema.fields
    block_length = schema.block_length

    fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")

    fixed_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        case Map.get(field_specs, name) do
          {:variable, _} -> false
          {:group, _} -> false
          nil -> false
          _ -> true
        end
      end)

    var_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        match?({:variable, _}, Map.get(field_specs, name))
      end)

    fixed_pairs =
      Enum.map(fixed_fields, fn {name, type, _opts} ->
        {type_mod, offset, _endian} = Map.fetch!(field_specs, name)
        value_expr = sql_json_value_expr(name, type, type_mod, offset)
        "'#{name}', #{value_expr}"
      end)

    {var_pairs, _} =
      Enum.map_reduce(var_fields, nil, fn {name, type, _opts}, prev_offset_expr ->
        offset_expr =
          case prev_offset_expr do
            nil -> "#{@header_size + block_length}"
            prev -> "#{prev} + 2 + gridcodec.read_u16(data, #{prev})"
          end

        value_expr = sql_json_var_value_expr(name, type, offset_expr)
        {"'#{name}', #{value_expr}", offset_expr}
      end)

    all_pairs = Enum.join(fixed_pairs ++ var_pairs, ",\n    ")

    """
    CREATE OR REPLACE FUNCTION gridcodec.decode_#{fn_name}_json(data bytea)
    RETURNS jsonb AS $$
    SELECT jsonb_build_object(
      #{all_pairs}
    );
    $$ LANGUAGE sql IMMUTABLE STRICT;

    """
  end

  defp sql_json_value_expr(_name, type, _type_mod, offset) do
    cond do
      enum_type?(type) ->
        table = enum_table_name(type)
        "(SELECT e.name FROM gridcodec_enums.#{table} e WHERE e.id = get_byte(data, #{offset}))"

      type == :u8 ->
        "CASE WHEN get_byte(data, #{offset}) = 255 THEN NULL ELSE get_byte(data, #{offset}) END"

      type == :i8 ->
        "CASE WHEN gridcodec.read_i8(data, #{offset}) = -128 THEN NULL ELSE gridcodec.read_i8(data, #{offset}) END"

      type == :u16 ->
        "CASE WHEN gridcodec.read_u16(data, #{offset}) = 65535 THEN NULL ELSE gridcodec.read_u16(data, #{offset}) END"

      type == :i16 ->
        "CASE WHEN gridcodec.read_i16(data, #{offset}) = -32768 THEN NULL ELSE gridcodec.read_i16(data, #{offset}) END"

      type == :u32 ->
        "CASE WHEN gridcodec.read_u32(data, #{offset}) = 4294967295 THEN NULL ELSE gridcodec.read_u32(data, #{offset}) END"

      type == :i32 ->
        "CASE WHEN gridcodec.read_i32(data, #{offset}) = -2147483648 THEN NULL ELSE gridcodec.read_i32(data, #{offset}) END"

      type == :u64 ->
        "CASE WHEN gridcodec.read_u64(data, #{offset}) = 18446744073709551615 THEN NULL ELSE gridcodec.read_u64(data, #{offset}) END"

      type == :i64 ->
        "CASE WHEN gridcodec.read_i64(data, #{offset}) = -9223372036854775808 THEN NULL ELSE gridcodec.read_i64(data, #{offset}) END"

      type in [:uuid, :uuid_string] ->
        "gridcodec.read_uuid_nullable(data, #{offset})::text"

      prefixed_id_type?(type) ->
        prefix = prefixed_id_prefix(type)

        "CASE WHEN get_byte(data, #{offset}) = 0" <>
          " AND substring(data FROM #{offset + 2} FOR 16) = '\\x00000000000000000000000000000000'::bytea" <>
          " THEN NULL" <>
          " ELSE '#{prefix}' || encode(substring(data FROM #{offset + 2} FOR 16), 'hex')::uuid::text" <>
          " END"

      type == :bool ->
        "gridcodec.read_bool(data, #{offset})"

      type == :decimal ->
        "gridcodec.read_decimal(data, #{offset})"

      type in [:timestamp_us, :datetime_us] ->
        "gridcodec.read_timestamp_us(data, #{offset})"

      true ->
        "NULL"
    end
  end

  defp sql_json_var_value_expr(_name, type, offset_expr) do
    case type do
      t when t in [:string, :string16] ->
        "gridcodec.read_string16(data, (#{offset_expr})::int)"

      _ ->
        "NULL"
    end
  end

  # ============================================================================
  # Private: Type → SQL Mapping
  # ============================================================================

  defp sql_column_type(type) when is_atom(type) do
    cond do
      type in [:u8, :i8] -> "smallint"
      type in [:u16, :i16] -> "integer"
      type in [:u32, :i32] -> "bigint"
      type in [:u64, :i64] -> "numeric"
      type in [:f32, :f64] -> "double precision"
      type == :uuid -> "uuid"
      type == :uuid_string -> "uuid"
      type == :bool -> "boolean"
      type == :decimal -> "numeric"
      type in [:timestamp_us, :timestamp_ns, :datetime_us, :datetime_ns] -> "timestamptz"
      type in [:string, :string8, :string16, :string32] -> "text"
      enum_type?(type) -> "text"
      prefixed_id_type?(type) -> "text"
      true -> "text"
    end
  end

  defp sql_column_type({:decimal, _opts}), do: "numeric"
  defp sql_column_type({:positive_decimal, _opts}), do: "numeric"
  defp sql_column_type({_type, _opts}), do: "text"

  defp sql_read_expr(name, type, type_mod, offset) do
    cond do
      prefixed_id_type?(type) ->
        prefix = prefixed_id_prefix(type)

        "CASE WHEN get_byte(data, #{offset}) = 0" <>
          " AND substring(data FROM #{offset + 2} FOR 16) = '\\x00000000000000000000000000000000'::bytea" <>
          " THEN NULL" <>
          " ELSE '#{prefix}' || encode(substring(data FROM #{offset + 2} FOR 16), 'hex')::uuid::text" <>
          " END AS \"#{name}\""

      enum_type?(type) ->
        table = enum_table_name(type)

        "(SELECT e.name FROM gridcodec_enums.#{table} e WHERE e.id = get_byte(data, #{offset})) AS \"#{name}\""

      true ->
        null_expr = null_check_expr(type, type_mod, offset)

        read =
          cond do
            type == :u8 ->
              "gridcodec.read_u8(data, #{offset})"

            type == :i8 ->
              "gridcodec.read_i8(data, #{offset})"

            type == :u16 ->
              "gridcodec.read_u16(data, #{offset})"

            type == :i16 ->
              "gridcodec.read_i16(data, #{offset})"

            type == :u32 ->
              "gridcodec.read_u32(data, #{offset})"

            type == :i32 ->
              "gridcodec.read_i32(data, #{offset})"

            type == :u64 ->
              "gridcodec.read_u64(data, #{offset})"

            type == :i64 ->
              "gridcodec.read_i64(data, #{offset})"

            type in [:uuid, :uuid_string] ->
              "gridcodec.read_uuid_nullable(data, #{offset})"

            type == :bool ->
              "gridcodec.read_bool(data, #{offset})"

            type == :decimal ->
              "gridcodec.read_decimal(data, #{offset})"

            match?({:decimal, _}, type) ->
              "gridcodec.read_i64(data, #{offset})"

            match?({:positive_decimal, _}, type) ->
              "gridcodec.read_u64(data, #{offset})"

            type in [:timestamp_us, :datetime_us] ->
              "gridcodec.read_timestamp_us(data, #{offset})"

            true ->
              "'unsupported:#{inspect(type)}'::text"
          end

        case null_expr do
          nil -> "#{read} AS \"#{name}\""
          check -> "CASE WHEN #{check} THEN NULL ELSE #{read} END AS \"#{name}\""
        end
    end
  end

  defp sql_read_var_expr(name, type, offset_expr) do
    case type do
      t when t in [:string, :string16] ->
        "gridcodec.read_string16(data, (#{offset_expr})::int) AS \"#{name}\""

      :string8 ->
        "'unsupported:string8'::text AS \"#{name}\""

      _ ->
        "'unsupported:#{type}'::text AS \"#{name}\""
    end
  end

  defp null_check_expr(type, _type_mod, offset) do
    cond do
      type == :u8 ->
        "get_byte(data, #{offset}) = 255"

      type == :i8 ->
        "gridcodec.read_i8(data, #{offset}) = -128"

      type == :u16 ->
        "gridcodec.read_u16(data, #{offset}) = 65535"

      type == :i16 ->
        "gridcodec.read_i16(data, #{offset}) = -32768"

      type == :u32 ->
        "gridcodec.read_u32(data, #{offset}) = 4294967295"

      type == :i32 ->
        "gridcodec.read_i32(data, #{offset}) = -2147483648"

      type == :u64 ->
        "gridcodec.read_u64(data, #{offset}) = 18446744073709551615"

      type == :i64 ->
        "gridcodec.read_i64(data, #{offset}) = -9223372036854775808"

      type in [
        :uuid,
        :uuid_string,
        :bool,
        :decimal,
        :timestamp_us,
        :timestamp_ns,
        :datetime_us,
        :datetime_ns
      ] ->
        nil

      prefixed_id_type?(type) ->
        "get_byte(data, #{offset}) = 0" <>
          " AND substring(data FROM #{offset + 2} FOR 16) = '\\x00000000000000000000000000000000'::bytea"

      true ->
        nil
    end
  end
end
