defmodule GridCodec.SQL do
  @moduledoc """
  Generates PostgreSQL functions for decoding GridCodec binaries stored as `bytea`.

  Produces pure SQL functions that extract typed fields from GridCodec binaries
  at their compile-time-known offsets. No PostgreSQL extension required.

  ## Usage

      # Generate SQL for a single codec
      sql = GridCodec.SQL.generate(MyApp.Events.OrderSubmitted)

      # Generate SQL for all registered codecs
      sql = GridCodec.SQL.generate_all()

      # Generate a consumer-owned indexed stream decoder
      stream_sql =
        GridCodec.SQL.generate_stream_decoder(
          function: "risk.decode_user_stream",
          table: "risk.recorded_events",
          stream_id_type: :uuid,
          stream_id_column: :stream_uuid,
          decode: {:typed, MyApp.Events.OrderSubmitted}
        )

      # Write to file
      GridCodec.SQL.generate_all_to_file("priv/gridcodec_functions.sql")

  ## Generated Functions

  For each codec, generates:
  - `gridcodec.decode_<type_name>(bytea)` — full decode returning a row with typed columns
  - Enum lookup tables in `gridcodec_enums` schema

  Shared helper functions:
  - `gridcodec.read_header(bytea)` — parse the 8-byte header
  - `gridcodec.read_u8(bytea, int)`, `read_u16(...)`, etc. — type extractors
  - `gridcodec.read_decimal(bytea, int)` — mantissa/exponent → `numeric`
  - `gridcodec.read_timestamp_us(bytea, int)` — microseconds → `timestamptz`

  Fixed repeating groups are returned as `jsonb` arrays. Group and var-data
  offsets are derived from the block lengths and counts in each wire header,
  so newer fixed blocks and group entries can be skipped safely.
  """

  @header_size 8
  @stream_id_types %{
    bigint: "bigint",
    integer: "integer",
    text: "text",
    uuid: "uuid"
  }

  @doc """
  Generates the shared SQL helper functions and schema setup.
  """
  def generate_helpers do
    """
    -- ============================================================
    -- GridCodec PostgreSQL Helpers
    -- Generated by GridCodec.SQL
    -- ============================================================

    CREATE SCHEMA IF NOT EXISTS gridcodec;
    CREATE SCHEMA IF NOT EXISTS gridcodec_enums;

    -- Header parser: 8 bytes → {block_length, template_id, schema_id, version}
    CREATE OR REPLACE FUNCTION gridcodec.read_header(data bytea)
    RETURNS TABLE (block_length int, template_id int, schema_id int, version int)
    AS $$
    SELECT
      get_byte(data, 0) + get_byte(data, 1) * 256,
      get_byte(data, 2) + get_byte(data, 3) * 256,
      get_byte(data, 4) + get_byte(data, 5) * 256,
      get_byte(data, 6) + get_byte(data, 7) * 256;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Unsigned integer readers (little-endian)
    CREATE OR REPLACE FUNCTION gridcodec.read_u8(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT get_byte(data, pos)::smallint;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u16(data bytea, pos int)
    RETURNS integer AS $$
      SELECT (get_byte(data, pos) + get_byte(data, pos + 1) * 256)::integer;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u32(data bytea, pos int)
    RETURNS bigint AS $$
      SELECT (get_byte(data, pos)::bigint
            + get_byte(data, pos + 1)::bigint * 256
            + get_byte(data, pos + 2)::bigint * 65536
            + get_byte(data, pos + 3)::bigint * 16777216);
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_u64(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT (get_byte(data, pos)::numeric
            + get_byte(data, pos + 1)::numeric * 256
            + get_byte(data, pos + 2)::numeric * 65536
            + get_byte(data, pos + 3)::numeric * 16777216
            + get_byte(data, pos + 4)::numeric * 4294967296
            + get_byte(data, pos + 5)::numeric * 1099511627776
            + get_byte(data, pos + 6)::numeric * 281474976710656
            + get_byte(data, pos + 7)::numeric * 72057594037927936);
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Signed integer readers (little-endian, two's complement)
    CREATE OR REPLACE FUNCTION gridcodec.read_i8(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT CASE
        WHEN get_byte(data, pos) >= 128
        THEN (get_byte(data, pos) - 256)::smallint
        ELSE get_byte(data, pos)::smallint
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i16(data bytea, pos int)
    RETURNS integer AS $$
      SELECT CASE
        WHEN gridcodec.read_u16(data, pos) >= 32768
        THEN (gridcodec.read_u16(data, pos) - 65536)::integer
        ELSE gridcodec.read_u16(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i32(data bytea, pos int)
    RETURNS bigint AS $$
      SELECT CASE
        WHEN gridcodec.read_u32(data, pos) >= 2147483648
        THEN (gridcodec.read_u32(data, pos) - 4294967296)::bigint
        ELSE gridcodec.read_u32(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_i64(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT CASE
        WHEN get_byte(data, pos + 7) >= 128
        THEN gridcodec.read_u64(data, pos) - 18446744073709551616::numeric
        ELSE gridcodec.read_u64(data, pos)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Native signed i64 reader for fields that fit PostgreSQL bigint exactly
    CREATE OR REPLACE FUNCTION gridcodec.read_i64_bigint(data bytea, pos int)
    RETURNS bigint AS $$
      SELECT get_byte(data, pos)::bigint
           | (get_byte(data, pos + 1)::bigint << 8)
           | (get_byte(data, pos + 2)::bigint << 16)
           | (get_byte(data, pos + 3)::bigint << 24)
           | (get_byte(data, pos + 4)::bigint << 32)
           | (get_byte(data, pos + 5)::bigint << 40)
           | (get_byte(data, pos + 6)::bigint << 48)
           | (get_byte(data, pos + 7)::bigint << 56);
    $$ LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE;

    -- UUID reader: 16 bytes → uuid
    CREATE OR REPLACE FUNCTION gridcodec.read_uuid(data bytea, pos int)
    RETURNS uuid AS $$
      SELECT encode(substring(data FROM pos + 1 FOR 16), 'hex')::uuid;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- UUID null check (all zeros = null)
    CREATE OR REPLACE FUNCTION gridcodec.read_uuid_nullable(data bytea, pos int)
    RETURNS uuid AS $$
      SELECT CASE
        WHEN substring(data FROM pos + 1 FOR 16) = '\\x00000000000000000000000000000000'::bytea
        THEN NULL
        ELSE encode(substring(data FROM pos + 1 FOR 16), 'hex')::uuid
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Fixed char array reader: trim at the first zero byte before UTF-8 conversion
    CREATE OR REPLACE FUNCTION gridcodec.read_char_array(data bytea, pos int, len int)
    RETURNS text AS $$
      SELECT convert_from(
        CASE
          WHEN position('\\x00'::bytea IN substring(data FROM pos + 1 FOR len)) = 0
          THEN substring(data FROM pos + 1 FOR len)
          ELSE substring(
            data
            FROM pos + 1
            FOR position('\\x00'::bytea IN substring(data FROM pos + 1 FOR len)) - 1
          )
        END,
        'UTF8'
      );
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Decimal reader: 8 bytes mantissa (i64 LE) + 1 byte exponent (i8) → numeric
    CREATE OR REPLACE FUNCTION gridcodec.read_decimal(data bytea, pos int)
    RETURNS numeric AS $$
      SELECT CASE
        WHEN gridcodec.read_i64(data, pos) = -9223372036854775808::numeric
        THEN NULL
        ELSE gridcodec.read_i64(data, pos) * power(10, CASE
          WHEN get_byte(data, pos + 8) >= 128
          THEN get_byte(data, pos + 8) - 256
          ELSE get_byte(data, pos + 8)
        END)
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Timestamp reader: i64 microseconds → timestamptz
    CREATE OR REPLACE FUNCTION gridcodec.read_timestamp_us(data bytea, pos int)
    RETURNS timestamptz AS $$
      SELECT CASE
        WHEN gridcodec.read_i64_bigint(data, pos) = 0
        THEN NULL
        ELSE to_timestamp(
          gridcodec.read_i64_bigint(data, pos)::double precision / 1000000.0
        )
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE;

    -- PrefixedId reader: 1 byte tag + 16 byte UUID → tag:uuid text
    -- Null: tag=0 and uuid=all-zeros
    CREATE OR REPLACE FUNCTION gridcodec.read_prefixed_id(data bytea, pos int)
    RETURNS text AS $$
      SELECT CASE
        WHEN get_byte(data, pos) = 0
         AND substring(data FROM pos + 2 FOR 16) = '\\x00000000000000000000000000000000'::bytea
        THEN NULL
        ELSE encode(substring(data FROM pos + 2 FOR 16), 'hex')::uuid::text
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    CREATE OR REPLACE FUNCTION gridcodec.read_prefixed_id_tag(data bytea, pos int)
    RETURNS smallint AS $$
      SELECT get_byte(data, pos)::smallint;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- Bool reader: 0=false, 1=true, 255=null
    CREATE OR REPLACE FUNCTION gridcodec.read_bool(data bytea, pos int)
    RETURNS boolean AS $$
      SELECT CASE get_byte(data, pos)
        WHEN 0 THEN false
        WHEN 255 THEN NULL
        ELSE true
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;

    -- String16 reader: 2-byte LE length prefix + data
    CREATE OR REPLACE FUNCTION gridcodec.read_string16(data bytea, pos int)
    RETURNS text AS $$
      SELECT CASE gridcodec.read_u16(data, pos)
        WHEN 0 THEN NULL
        ELSE convert_from(
          substring(data FROM pos + 3 FOR gridcodec.read_u16(data, pos)),
          'UTF8'
        )
      END;
    $$ LANGUAGE sql IMMUTABLE STRICT;
    """
  end

  @doc """
  Generates SQL for a single codec module.
  """
  def generate(module) when is_atom(module) do
    schema = module.__schema__()
    type_name = module.__type__()
    field_specs = module.__field_specs__()
    fields = schema.fields
    block_length = schema.block_length
    groups = build_group_specs!(module, schema)

    fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")

    enum_tables =
      generate_enum_tables(fields ++ group_fields(schema) ++ group_enum_fields(groups))

    decode_fn =
      generate_decode_function(
        fn_name,
        type_name,
        module,
        fields,
        field_specs,
        block_length,
        groups
      )

    enum_tables <> decode_fn <> generate_field_readers(module)
  end

  @doc """
  Generates one direct PostgreSQL scalar reader for a fixed codec field.

  Readers avoid full-row and JSONB materialization and are suitable for
  filters, aggregates, expression indexes, and selective stream projections.
  Variable-length and group fields do not have compile-time-fixed offsets and
  are rejected.
  """
  def generate_field_reader(module, field) when is_atom(module) and is_atom(field) do
    {name, type, type_mod, offset} = fixed_field!(module, field)
    opts = field_options(module, field)
    fn_name = module.__type__() |> sql_function_part()
    generate_field_reader_function(fn_name, name, type, type_mod, offset, opts)
  end

  @doc """
  Generates direct PostgreSQL scalar readers for every fixed field in a codec.
  """
  def generate_field_readers(module) when is_atom(module) do
    module
    |> fixed_fields()
    |> Enum.filter(fn {_name, type, type_mod, offset} ->
      not is_nil(sql_fast_value_expr(type, type_mod, offset))
    end)
    |> Enum.map_join("\n", fn {name, type, type_mod, offset} ->
      fn_name = module.__type__() |> sql_function_part()
      opts = field_options(module, name)
      generate_field_reader_function(fn_name, name, type, type_mod, offset, opts)
    end)
  end

  @doc """
  Generates SQL for all registered GridCodec codecs.

  Pass an explicit list of modules for reliable results in scripts,
  or call with no arguments to scan all loaded modules.

      GridCodec.SQL.generate_all()
      GridCodec.SQL.generate_all([MyApp.Events.OrderCreated, MyApp.Events.TradeFilled])
  """
  def generate_all(modules \\ nil) do
    codecs =
      case modules do
        nil ->
          :code.all_loaded()
          |> Enum.map(fn {mod, _} -> mod end)
          |> Enum.filter(&gridcodec_codec?/1)

        mods when is_list(mods) ->
          Enum.filter(mods, &gridcodec_codec?/1)
      end
      |> Enum.sort_by(& &1.__type__())

    {supported_codecs, skipped_codecs} = Enum.split_with(codecs, &sql_generation_supported?/1)

    helpers = generate_helpers()
    skipped_comments = skipped_codec_comments(skipped_codecs)
    codec_sql = Enum.map_join(supported_codecs, "\n", &generate/1)
    universal_decoder = generate_universal_decoder(supported_codecs)

    helpers <> "\n" <> skipped_comments <> codec_sql <> "\n" <> universal_decoder
  end

  @doc """
  Generates the catalog as individually executable migration statements.

  This avoids consumer-side SQL regexes that can silently omit newly generated
  function shapes.
  """
  def generate_all_statements(modules \\ nil) do
    modules
    |> generate_all()
    |> split_statements()
  end

  @doc """
  Splits SQL generated by this module into executable top-level statements.
  """
  def split_statements(sql) when is_binary(sql) do
    split_sql(sql, :normal, [], [])
  end

  defp split_sql(<<>>, _state, current, statements) do
    statements
    |> maybe_add_statement(current)
    |> Enum.reverse()
  end

  defp split_sql(<<"--", rest::binary>>, :normal, current, statements) do
    split_sql(rest, :line_comment, ["--" | current], statements)
  end

  defp split_sql(<<"'", rest::binary>>, :normal, current, statements) do
    split_sql(rest, :single_quote, ["'" | current], statements)
  end

  defp split_sql(<<"\"", rest::binary>>, :normal, current, statements) do
    split_sql(rest, :double_quote, ["\"" | current], statements)
  end

  defp split_sql(<<"$", _rest::binary>> = sql, :normal, current, statements) do
    case Regex.run(~r/^\$(?:[A-Za-z_][A-Za-z0-9_]*)?\$/, sql) do
      [tag] ->
        rest = binary_part(sql, byte_size(tag), byte_size(sql) - byte_size(tag))
        split_sql(rest, {:dollar_quote, tag}, [tag | current], statements)

      nil ->
        consume_sql_codepoint(sql, :normal, current, statements)
    end
  end

  defp split_sql(<<";", rest::binary>>, :normal, current, statements) do
    statements = maybe_add_statement(statements, [";" | current])
    split_sql(rest, :normal, [], statements)
  end

  defp split_sql(<<"\n", rest::binary>>, :line_comment, current, statements) do
    split_sql(rest, :normal, ["\n" | current], statements)
  end

  defp split_sql(<<"''", rest::binary>>, :single_quote, current, statements) do
    split_sql(rest, :single_quote, ["''" | current], statements)
  end

  defp split_sql(<<"'", rest::binary>>, :single_quote, current, statements) do
    split_sql(rest, :normal, ["'" | current], statements)
  end

  defp split_sql(<<"\"\"", rest::binary>>, :double_quote, current, statements) do
    split_sql(rest, :double_quote, ["\"\"" | current], statements)
  end

  defp split_sql(<<"\"", rest::binary>>, :double_quote, current, statements) do
    split_sql(rest, :normal, ["\"" | current], statements)
  end

  defp split_sql(sql, {:dollar_quote, tag}, current, statements) do
    if String.starts_with?(sql, tag) do
      rest = binary_part(sql, byte_size(tag), byte_size(sql) - byte_size(tag))
      split_sql(rest, :normal, [tag | current], statements)
    else
      consume_sql_codepoint(sql, {:dollar_quote, tag}, current, statements)
    end
  end

  defp split_sql(sql, state, current, statements) do
    consume_sql_codepoint(sql, state, current, statements)
  end

  defp consume_sql_codepoint(<<codepoint::utf8, rest::binary>>, state, current, statements) do
    split_sql(rest, state, [<<codepoint::utf8>> | current], statements)
  end

  defp maybe_add_statement(statements, current) do
    statement =
      current
      |> Enum.reverse()
      |> IO.iodata_to_binary()
      |> String.trim()

    if statement == "", do: statements, else: [statement | statements]
  end

  @doc """
  Generates the drops required before refreshing a catalog in a migration.

  PostgreSQL cannot replace functions when their return row shape changes.
  Execute this SQL before `generate_all/1` when codecs add decoded columns.
  The operation is idempotent.
  """
  def generate_drop_all(modules) when is_list(modules) do
    modules
    |> drop_statements()
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  @doc """
  Returns individually executable, idempotent catalog-drop statements.
  """
  def drop_statements(modules) when is_list(modules) do
    codec_drops =
      modules
      |> Enum.filter(&gridcodec_codec?/1)
      |> Enum.uniq_by(& &1.__type__())
      |> Enum.sort_by(& &1.__type__())
      |> Enum.flat_map(&codec_drop_statements/1)

    [
      "CREATE SCHEMA IF NOT EXISTS gridcodec;",
      "DROP FUNCTION IF EXISTS gridcodec.decode(text, bytea);"
      | codec_drops
    ]
  end

  @doc """
  Generates SQL and writes it to a file.
  """
  def generate_all_to_file(path, modules \\ nil) do
    sql = generate_all(modules)
    File.write!(path, sql)
    {:ok, path}
  end

  @doc """
  Generates a set-returning PostgreSQL function for one indexed event stream.

  The consumer supplies its table and function names because GridCodec does not
  own an event-envelope schema. The generated function filters on the native
  stream-id type before decoding, preserving use of a `(stream_id,
  stream_version)` index.

  Required options:

  - `:function` — qualified function name, for example `"risk.decode_user_stream"`
  - `:table` — qualified event table name, for example `"risk.recorded_events"`

  Optional options:

  - `:stream_id_type` — `:text`, `:uuid`, `:bigint`, or `:integer` (default: `:text`)
  - `:stream_id_column` — stream identifier column (default: `:stream_id`)
  - `:stream_version_column` — ordering column (default: `:stream_version`)
  - `:event_type_column` — GridCodec type-name column (default: `:event_type`)
  - `:data_column` — GridCodec `bytea` column (default: `:data`)
  - `:decode` — representation mode (default: `:jsonb`):
    - `:raw` returns the original `bytea` for BEAM decoding
    - `{:typed, CodecModule}` returns every supported top-level field as a
      native column in one set-based query
    - `{:fields, CodecModule, fields}` returns selected fixed fields as native
      columns and filters the stream to that codec's type
    - `:jsonb` returns a fully decoded JSONB payload

  The event table should have an index beginning with the stream-id and version
  columns. All identifiers are validated and quoted.
  """
  def generate_stream_decoder(opts) when is_list(opts) do
    function_name = opts |> Keyword.fetch!(:function) |> qualified_identifier!()
    table_name = opts |> Keyword.fetch!(:table) |> qualified_identifier!()
    stream_id_type = opts |> Keyword.get(:stream_id_type, :text) |> stream_id_type!()
    stream_id_column = opts |> Keyword.get(:stream_id_column, :stream_id) |> identifier!()

    stream_version_column =
      opts |> Keyword.get(:stream_version_column, :stream_version) |> identifier!()

    event_type_column = opts |> Keyword.get(:event_type_column, :event_type) |> identifier!()
    data_column = opts |> Keyword.get(:data_column, :data) |> identifier!()
    decode = Keyword.get(opts, :decode, :jsonb)

    {return_columns, payload_selects, event_type_filter, mode_description} =
      stream_decode_spec!(decode, event_type_column, data_column)

    select_columns =
      [
        "events.#{stream_version_column}::bigint AS stream_version",
        "events.#{event_type_column}::text AS event_type"
        | payload_selects
      ]
      |> Enum.join(",\n  ")

    where_clauses =
      ["events.#{stream_id_column} = target_stream_id", event_type_filter]
      |> Enum.reject(&is_nil/1)
      |> Enum.join("\n  AND ")

    """
    -- Set-based #{mode_description} for an indexed consumer-owned event stream
    CREATE OR REPLACE FUNCTION #{function_name}(target_stream_id #{stream_id_type})
    RETURNS TABLE (#{return_columns})
    AS $$
    SELECT
      #{select_columns}
    FROM #{table_name} AS events
    WHERE #{where_clauses}
    ORDER BY events.#{stream_version_column};
    $$ LANGUAGE sql STABLE ROWS 1000;
    """
  end

  @doc """
  Generates the idempotent drop required before changing a stream decoder's
  return shape.
  """
  def drop_stream_decoder_statement(opts) when is_list(opts) do
    function_name = opts |> Keyword.fetch!(:function) |> qualified_identifier!()
    stream_id_type = opts |> Keyword.get(:stream_id_type, :text) |> stream_id_type!()
    "DROP FUNCTION IF EXISTS #{function_name}(#{stream_id_type});"
  end

  defp stream_decode_spec!(:jsonb, event_type_column, data_column) do
    {
      "stream_version bigint, event_type text, decoded jsonb",
      [
        "gridcodec.decode(events.#{event_type_column}::text, events.#{data_column}) AS decoded"
      ],
      nil,
      "JSONB decoder"
    }
  end

  defp stream_decode_spec!(:raw, _event_type_column, data_column) do
    {
      "stream_version bigint, event_type text, data bytea",
      ["events.#{data_column} AS data"],
      nil,
      "raw reader"
    }
  end

  defp stream_decode_spec!({:typed, module}, event_type_column, data_column)
       when is_atom(module) do
    unless gridcodec_codec?(module) do
      raise ArgumentError, "not a GridCodec module: #{inspect(module)}"
    end

    fields = native_typed_fields!(module, "events.#{data_column}")

    return_fields =
      Enum.map_join(fields, ", ", fn {name, type, _expression} ->
        ~s("#{name}" #{sql_column_type(type)})
      end)

    selects =
      Enum.map(fields, fn {name, _type, expression} ->
        ~s|#{expression} AS "#{name}"|
      end)

    {
      "stream_version bigint, event_type text, #{return_fields}",
      selects,
      "events.#{event_type_column} = #{sql_literal(module.__type__())}",
      "native typed projection"
    }
  end

  defp stream_decode_spec!({:fields, module, fields}, event_type_column, data_column)
       when is_atom(module) and is_list(fields) and fields != [] do
    unless gridcodec_codec?(module) do
      raise ArgumentError, "not a GridCodec module: #{inspect(module)}"
    end

    field_specs = Enum.map(fields, &fixed_field!(module, &1))
    fn_name = module.__type__() |> sql_function_part()

    return_fields =
      Enum.map_join(field_specs, ", ", fn {name, type, _type_mod, _offset} ->
        ~s("#{name}" #{sql_column_type(type)})
      end)

    selects =
      Enum.map(field_specs, fn {name, _type, _type_mod, _offset} ->
        reader = "gridcodec.read_#{fn_name}_#{sql_function_part(name)}"
        ~s|#{reader}(events.#{data_column}) AS "#{name}"|
      end)

    {
      "stream_version bigint, event_type text, #{return_fields}",
      selects,
      "events.#{event_type_column} = #{sql_literal(module.__type__())}",
      "fixed-field projection"
    }
  end

  defp stream_decode_spec!({:fields, _module, []}, _event_type_column, _data_column) do
    raise ArgumentError, "field projection requires at least one fixed field"
  end

  defp stream_decode_spec!(decode, _event_type_column, _data_column) do
    raise ArgumentError, "unsupported stream decode mode: #{inspect(decode)}"
  end

  defp native_typed_fields!(module, data) do
    schema = module.__schema__()
    groups = build_group_specs!(module, schema)

    if groups != [] do
      raise ArgumentError,
            "native typed projection does not support repeating groups for #{inspect(module)}"
    end

    field_specs = module.__field_specs__()
    variable_expressions = native_variable_expressions!(schema.fields, field_specs, data)

    fields =
      Enum.flat_map(schema.fields, fn {name, type, opts} ->
        case Map.get(field_specs, name) do
          {type_mod, offset, _endian} ->
            case sql_fast_value_expr(type, type_mod, offset, opts, data) do
              nil ->
                raise ArgumentError,
                      "native typed projection does not support field #{inspect(name)} type #{inspect(type)}"

              expression ->
                [{name, type, expression}]
            end

          {:variable, _index} ->
            [{name, type, Map.fetch!(variable_expressions, name)}]

          nil ->
            []
        end
      end)

    if fields == [] do
      raise ArgumentError, "native typed projection requires at least one supported field"
    end

    fields
  end

  defp native_variable_expressions!(fields, field_specs, data) do
    variable_fields =
      Enum.filter(fields, fn {name, _type, _opts} ->
        match?({:variable, _index}, Map.get(field_specs, name))
      end)

    start_offset = "#{@header_size} + gridcodec.read_u16(#{data}, 0)"

    {expressions, _next_offset} =
      Enum.map_reduce(variable_fields, start_offset, fn {name, type, opts}, offset ->
        expression =
          case type do
            value when value in [:string, :string16] ->
              "gridcodec.read_string16(#{data}, (#{offset})::int)"

            _other ->
              raise ArgumentError,
                    "native typed projection does not support variable field #{inspect(name)} type #{inspect(type)}"
          end

        next_offset = "#{offset} + 2 + gridcodec.read_u16(#{data}, (#{offset})::int)"
        {{name, guard_since(expression, opts, data)}, next_offset}
      end)

    Map.new(expressions)
  end

  defp gridcodec_codec?(mod) do
    Code.ensure_loaded?(mod) and
      function_exported?(mod, :__gridcodec_struct__?, 0) and
      function_exported?(mod, :__field_specs__, 0) and
      function_exported?(mod, :__type__, 0)
  end

  defp qualified_identifier!(value) do
    value
    |> identifier_string!()
    |> String.split(".")
    |> case do
      [_name] = parts -> Enum.map_join(parts, ".", &quote_identifier!/1)
      [_schema, _name] = parts -> Enum.map_join(parts, ".", &quote_identifier!/1)
      _parts -> raise ArgumentError, "invalid SQL identifier: #{inspect(value)}"
    end
  end

  defp identifier!(value) do
    value
    |> identifier_string!()
    |> quote_identifier!()
  end

  defp identifier_string!(value) when is_atom(value), do: Atom.to_string(value)
  defp identifier_string!(value) when is_binary(value), do: value

  defp identifier_string!(value) do
    raise ArgumentError, "invalid SQL identifier: #{inspect(value)}"
  end

  defp quote_identifier!(value) do
    if Regex.match?(~r/^[A-Za-z_][A-Za-z0-9_$]*$/, value) do
      ~s("#{value}")
    else
      raise ArgumentError, "invalid SQL identifier: #{inspect(value)}"
    end
  end

  defp sql_function_part(value) do
    value
    |> identifier_string!()
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9_]/, "_")
  end

  defp sql_literal(value) when is_atom(value), do: value |> Atom.to_string() |> sql_literal()

  defp sql_literal(value) when is_binary(value),
    do: "'" <> String.replace(value, "'", "''") <> "'"

  defp stream_id_type!(type) do
    case Map.fetch(@stream_id_types, type) do
      {:ok, sql_type} -> sql_type
      :error -> raise ArgumentError, "unsupported stream_id_type: #{inspect(type)}"
    end
  end

  defp sql_generation_supported?(module) do
    schema = module.__schema__()
    batch_names = schema |> Map.get(:batches, []) |> Enum.map(&elem(&1, 0)) |> MapSet.new()

    Enum.all?(Map.get(schema, :groups, []), fn {name, _block, opts} ->
      not MapSet.member?(batch_names, name) and
        Keyword.get(opts, :framing) != :length_prefixed and
        is_integer(Keyword.get(opts, :block_length))
    end)
  end

  defp skipped_codec_comments([]), do: ""

  defp skipped_codec_comments(modules) do
    comments =
      Enum.map_join(modules, "\n", fn module ->
        "-- Skipped #{inspect(module)}: PostgreSQL SQL generation does not support one or more group layouts."
      end)

    comments <> "\n\n"
  end

  defp codec_drop_statements(module) do
    fn_name = module.__type__() |> sql_function_part()

    field_reader_drops =
      module
      |> fixed_fields()
      |> Enum.filter(fn {_name, type, type_mod, offset} ->
        not is_nil(sql_fast_value_expr(type, type_mod, offset))
      end)
      |> Enum.map(fn {name, _type, _type_mod, _offset} ->
        "DROP FUNCTION IF EXISTS gridcodec.read_#{fn_name}_#{sql_function_part(name)}(bytea);"
      end)

    [
      "DROP FUNCTION IF EXISTS gridcodec.decode_#{fn_name}(bytea);",
      "DROP FUNCTION IF EXISTS gridcodec.decode_#{fn_name}_json(bytea);"
      | field_reader_drops
    ]
  end

  # ============================================================================
  # Private: Enum Table Generation
  # ============================================================================

  defp generate_enum_tables(fields) do
    fields
    |> Enum.filter(fn {_name, type, _opts} -> enum_type?(type) end)
    |> Enum.map(fn {_name, type, _opts} -> type end)
    |> Enum.uniq()
    |> Enum.map_join("\n", &generate_enum_table/1)
  end

  defp enum_type?(type) when is_atom(type) do
    case Code.ensure_compiled(type) do
      {:module, _} ->
        function_exported?(type, :to_atom, 1) and function_exported?(type, :to_integer, 1)

      _ ->
        false
    end
  end

  defp enum_type?({_type, _opts}), do: false
  defp enum_type?(_), do: false

  defp enum_encoding!(module) do
    case module.encoding() do
      encoding when encoding in [:u8, :u16, :u32] -> encoding
      encoding -> raise ArgumentError, "unsupported SQL enum encoding: #{inspect(encoding)}"
    end
  end

  defp enum_sql_id_type(module) do
    case enum_encoding!(module) do
      :u8 -> "smallint"
      :u16 -> "integer"
      :u32 -> "bigint"
    end
  end

  defp enum_sql_read_expr(module, data, offset) do
    case enum_encoding!(module) do
      :u8 -> "get_byte(#{data}, #{sql_offset(offset)})"
      :u16 -> "gridcodec.read_u16(#{data}, #{sql_offset(offset)})"
      :u32 -> "gridcodec.read_u32(#{data}, #{sql_offset(offset)})"
    end
  end

  defp enum_inline_case_expr(module, data, offset) do
    clauses =
      module.values()
      |> Enum.map_join(" ", fn {name, value} ->
        "WHEN #{value} THEN #{sql_literal(name)}"
      end)

    "CASE #{enum_sql_read_expr(module, data, offset)} #{clauses} ELSE NULL END"
  end

  defp prefixed_id_type?(type) when is_atom(type) do
    case Code.ensure_compiled(type) do
      {:module, _} -> function_exported?(type, :__prefixed_id_meta__, 0)
      _ -> false
    end
  end

  defp prefixed_id_type?(_), do: false

  defp prefixed_id_prefix(type) do
    type.__prefixed_id_meta__().prefix
  end

  defp char_array_type?(type) when is_atom(type) do
    case Code.ensure_compiled(type) do
      {:module, _} -> function_exported?(type, :__char_array_meta__, 0)
      _ -> false
    end
  end

  defp char_array_type?(_), do: false

  defp sql_offset(offset) when is_integer(offset), do: Integer.to_string(offset)
  defp sql_offset(offset) when is_binary(offset), do: "(#{offset})"

  defp sql_offset_plus(offset, increment) when is_integer(offset), do: offset + increment

  defp sql_offset_plus(offset, increment) when is_binary(offset) do
    "(#{offset}) + #{increment}"
  end

  defp generate_enum_table(enum_module) do
    table_name = enum_table_name(enum_module)
    id_type = enum_sql_id_type(enum_module)

    values =
      if function_exported?(enum_module, :values, 0) do
        enum_module.values()
      else
        []
      end

    if values == [] do
      ""
    else
      rows =
        Enum.map_join(values, ",\n  ", fn {atom, int} ->
          "(#{int}, #{sql_literal(atom)})"
        end)

      """
      -- Enum: #{inspect(enum_module)}
      CREATE TABLE IF NOT EXISTS gridcodec_enums.#{table_name} (
        id #{id_type} PRIMARY KEY,
        name text NOT NULL
      );
      ALTER TABLE gridcodec_enums.#{table_name} ALTER COLUMN id TYPE #{id_type};
      TRUNCATE gridcodec_enums.#{table_name};
      INSERT INTO gridcodec_enums.#{table_name} (id, name) VALUES
        #{rows};

      """
    end
  end

  defp enum_table_name(module) do
    module
    |> Module.split()
    |> List.last()
    |> Macro.underscore()
  end

  # ============================================================================
  # Private: Fixed Group Layout
  # ============================================================================

  defp group_fields(schema) do
    schema
    |> Map.get(:group_fields, %{})
    |> Map.values()
    |> List.flatten()
  end

  defp group_enum_fields(groups) do
    Enum.flat_map(groups, fn
      %{entry: {:object, fields}} ->
        Enum.map(fields, fn field -> {field.name, field.type, []} end)

      %{entry: {:scalar, field}} ->
        [{:value, field.type, []}]
    end)
  end

  defp build_group_specs!(module, schema) do
    groups = Map.get(schema, :groups, [])
    var_fields = Map.get(schema, :var_fields, [])
    batch_names = schema |> Map.get(:batches, []) |> Enum.map(&elem(&1, 0)) |> MapSet.new()
    first_start = "#{@header_size} + gridcodec.read_u16(data, 0)"

    {specs, _next_start} =
      Enum.reduce(groups, {[], first_start}, fn {name, _block, opts}, {specs, start_expr} ->
        validate_sql_group!(module, name, opts, var_fields, batch_names)
        block_length = Keyword.fetch!(opts, :block_length)
        entry = group_entry_spec!(module, schema, name, opts)
        block_length_expr = "gridcodec.read_u16(data, (#{start_expr}))"
        count_expr = "gridcodec.read_u16(data, (#{start_expr}) + 2)"

        end_expr =
          "#{start_expr} + 4 + #{block_length_expr} * #{count_expr}"

        spec = %{
          name: name,
          start_expr: start_expr,
          end_expr: end_expr,
          block_length: block_length,
          block_length_expr: block_length_expr,
          count_expr: count_expr,
          entry: entry
        }

        {[spec | specs], end_expr}
      end)

    Enum.reverse(specs)
  end

  defp validate_sql_group!(module, name, opts, var_fields, batch_names) do
    framing = Keyword.get(opts, :framing)

    cond do
      MapSet.member?(batch_names, name) ->
        unsupported_group!(module, name, "batch-backed", var_fields)

      framing == :length_prefixed ->
        unsupported_group!(module, name, "length-prefixed", var_fields)

      not is_integer(Keyword.get(opts, :block_length)) ->
        unsupported_group!(module, name, "fixed group without block_length metadata", var_fields)

      true ->
        :ok
    end
  end

  defp unsupported_group!(module, name, kind, var_fields) do
    tail_context =
      case var_fields do
        [field | _] -> " before variable-length field #{inspect(field)}"
        [] -> ""
      end

    raise ArgumentError,
          "cannot generate PostgreSQL SQL for #{inspect(module)}: " <>
            "#{kind} group #{inspect(name)}#{tail_context} is not supported; " <>
            "only fixed groups with standard u16 blockLength/u16 numInGroup headers are supported"
  end

  defp group_entry_spec!(module, schema, name, opts) do
    of_type = Keyword.get(opts, :of)
    fields = Map.get(Map.get(schema, :group_fields, %{}), name, [])

    cond do
      gridcodec_codec?(of_type) ->
        {:object, typed_group_fields(of_type)}

      of_type != nil ->
        {type, type_mod} = resolve_sql_type!(of_type, [])

        {:scalar,
         %{name: :value, type: type, type_mod: type_mod, offset: 0, size: type_mod.size()}}

      fields != [] ->
        {:object, inline_group_fields(fields)}

      true ->
        raise ArgumentError,
              "cannot generate PostgreSQL SQL for #{inspect(module)}: " <>
                "fixed group #{inspect(name)} has no SQL-decodable entry metadata"
    end
  end

  defp typed_group_fields(module) do
    field_specs = module.__field_specs__(header: false)

    Enum.map(module.__schema__().fields, fn {name, type, opts} ->
      {type_mod, offset, _endian} = Map.fetch!(field_specs, name)

      %{
        name: name,
        type: type,
        type_mod: type_mod,
        offset: offset,
        size: type_mod.size(),
        opts: opts
      }
    end)
  end

  defp inline_group_fields(fields) do
    {field_specs, _offset} =
      Enum.map_reduce(fields, 0, fn {name, type, opts}, offset ->
        {normalized_type, type_mod} = resolve_sql_type!(type, opts)
        size = type_mod.size()

        spec = %{
          name: name,
          type: normalized_type,
          type_mod: type_mod,
          offset: offset,
          size: size,
          opts: opts
        }

        {spec, offset + size}
      end)

    field_specs
  end

  defp resolve_sql_type!(type, opts) do
    {type_atom, declared_type_opts} =
      case type do
        {atom, type_opts} when is_atom(atom) and is_list(type_opts) -> {atom, type_opts}
        atom when is_atom(atom) -> {atom, []}
      end

    type_opts = Keyword.get(opts, :__type_opts__, declared_type_opts)

    normalized_type =
      case type_opts do
        [] -> type_atom
        type_opts -> {type_atom, type_opts}
      end

    type_mod =
      case Keyword.get(opts, :__wire_module__) do
        nil ->
          case GridCodec.Type.lookup(type_atom) do
            {:ok, module} ->
              module

            {:error, :unknown_type} ->
              raise ArgumentError, "unsupported SQL group type: #{inspect(type)}"
          end

        module ->
          module
      end

    {normalized_type, type_mod}
  end

  defp var_data_start_expr([], _block_length), do: "#{@header_size} + gridcodec.read_u16(data, 0)"
  defp var_data_start_expr(groups, _block_length), do: List.last(groups).end_expr

  defp fixed_fields(module) do
    field_specs = module.__field_specs__()

    module.__schema__().fields
    |> Enum.flat_map(fn {name, type, _opts} ->
      case Map.get(field_specs, name) do
        {type_mod, offset, _endian} -> [{name, type, type_mod, offset}]
        _variable_or_group -> []
      end
    end)
  end

  defp field_options(module, field) do
    case Enum.find(module.__schema__().fields, fn {name, _type, _opts} -> name == field end) do
      {_name, _type, opts} -> opts
      nil -> []
    end
  end

  defp fixed_field!(module, field) do
    case Enum.find(fixed_fields(module), fn {name, _type, _type_mod, _offset} -> name == field end) do
      nil ->
        known_field? =
          Enum.any?(module.__schema__().fields, fn {name, _type, _opts} -> name == field end)

        if known_field? do
          raise ArgumentError,
                "#{inspect(module)} field #{inspect(field)} is not one of its fixed fields"
        else
          raise ArgumentError, "unknown field #{inspect(field)} for #{inspect(module)}"
        end

      fixed ->
        {_name, type, type_mod, offset} = fixed

        if is_nil(sql_fast_value_expr(type, type_mod, offset)) do
          raise ArgumentError,
                "cannot generate PostgreSQL field reader for #{inspect(field)} type #{inspect(type)}"
        end

        fixed
    end
  end

  defp group_json_expr(group) do
    entry_offset =
      "(#{group.start_expr}) + 4 + entry_index * #{group.block_length_expr}"

    entry_json =
      case group.entry do
        {:object, fields} ->
          pairs =
            Enum.map_join(fields, ", ", fn field ->
              "'#{field.name}', #{group_field_value_expr(field, group, entry_offset)}"
            end)

          "jsonb_build_object(#{pairs})"

        {:scalar, field} ->
          group_field_value_expr(field, group, entry_offset)
      end

    "COALESCE((SELECT jsonb_agg(#{entry_json} ORDER BY entry_index) " <>
      "FROM generate_series(0, #{group.count_expr} - 1) AS entries(entry_index)), " <>
      "'[]'::jsonb)"
  end

  defp group_field_value_expr(field, group, entry_offset) do
    field_offset =
      if field.offset == 0 do
        entry_offset
      else
        "#{entry_offset} + #{field.offset}"
      end

    value_expr = sql_json_value_expr(field.name, field.type, field.type_mod, field_offset)

    "CASE WHEN #{group.block_length_expr} < #{field.offset + field.size} " <>
      "THEN NULL ELSE #{value_expr} END"
  end

  # ============================================================================
  # Private: Decode Function Generation
  # ============================================================================

  defp generate_decode_function(
         fn_name,
         type_name,
         module,
         fields,
         field_specs,
         block_length,
         groups
       ) do
    fixed_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        case Map.get(field_specs, name) do
          {:variable, _} -> false
          {:group, _} -> false
          nil -> false
          _ -> true
        end
      end)

    var_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        match?({:variable, _}, Map.get(field_specs, name))
      end)

    columns =
      Enum.map(fixed_fields, fn {name, type, _opts} -> {name, sql_column_type(type)} end) ++
        Enum.map(groups, fn group -> {group.name, "jsonb"} end) ++
        Enum.map(var_fields, fn {name, type, _opts} -> {name, sql_column_type(type)} end)

    column_defs =
      Enum.map_join(columns, ",\n  ", fn {name, type} ->
        "\"#{name}\" #{type}"
      end)

    select_exprs =
      Enum.map(fixed_fields, fn {name, type, opts} ->
        {type_mod, offset, _endian} = Map.fetch!(field_specs, name)
        sql_read_expr(name, type, type_mod, offset, opts)
      end)

    group_select_exprs =
      Enum.map(groups, fn group ->
        "#{group_json_expr(group)} AS \"#{group.name}\""
      end)

    # Variable-length fields are sequential: each starts after the previous one's
    # 2-byte length prefix + content. We track the cumulative offset in SQL.
    {var_select_exprs, _} =
      Enum.map_reduce(var_fields, nil, fn {name, type, opts}, prev_offset_expr ->
        offset_expr =
          case prev_offset_expr do
            nil ->
              var_data_start_expr(groups, block_length)

            prev ->
              "#{prev} + 2 + gridcodec.read_u16(data, #{prev})"
          end

        expr = sql_read_var_expr(name, type, offset_expr, opts)
        {expr, offset_expr}
      end)

    all_exprs =
      Enum.map_join(select_exprs ++ group_select_exprs ++ var_select_exprs, ",\n  ", & &1)

    """
    -- Codec: #{inspect(module)}
    -- Type: "#{type_name}", block_length: #{block_length}
    CREATE OR REPLACE FUNCTION gridcodec.decode_#{fn_name}(data bytea)
    RETURNS TABLE (
      #{column_defs}
    ) AS $$
    SELECT
      #{all_exprs};
    $$ LANGUAGE sql IMMUTABLE STRICT;

    """
  end

  # ============================================================================
  # Private: Universal JSONB Decoder
  # ============================================================================

  defp generate_universal_decoder(codecs) do
    when_clauses =
      Enum.map_join(codecs, "\n    ", fn mod ->
        type_name = mod.__type__()
        fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")
        "WHEN type_name = '#{type_name}' THEN gridcodec.decode_#{fn_name}_json(data)"
      end)

    json_fns = Enum.map_join(codecs, "\n", &generate_json_function/1)

    json_fns <>
      """
      -- Universal decoder: returns any event as JSONB by type name
      --
      -- Usage:
      --   SELECT gridcodec.decode(event_type, data) FROM events;
      --   SELECT gridcodec.decode(event_type, data)->>'side' FROM events;
      --
      CREATE OR REPLACE FUNCTION gridcodec.decode(type_name text, data bytea)
      RETURNS jsonb AS $$
      SELECT CASE
        #{when_clauses}
        ELSE jsonb_build_object('_error', 'unknown type: ' || type_name)
      END;
      $$ LANGUAGE sql IMMUTABLE STRICT;

      """
  end

  defp generate_json_function(module) do
    schema = module.__schema__()
    type_name = module.__type__()
    field_specs = module.__field_specs__()
    fields = schema.fields
    block_length = schema.block_length
    groups = build_group_specs!(module, schema)

    fn_name = type_name |> String.downcase() |> String.replace(~r/[^a-z0-9_]/, "_")

    fixed_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        case Map.get(field_specs, name) do
          {:variable, _} -> false
          {:group, _} -> false
          nil -> false
          _ -> true
        end
      end)

    var_fields =
      fields
      |> Enum.filter(fn {name, _type, _opts} ->
        match?({:variable, _}, Map.get(field_specs, name))
      end)

    fixed_pairs =
      Enum.map(fixed_fields, fn {name, type, opts} ->
        {type_mod, offset, _endian} = Map.fetch!(field_specs, name)
        value_expr = sql_json_value_expr(name, type, type_mod, offset, opts)
        "'#{name}', #{value_expr}"
      end)

    group_pairs =
      Enum.map(groups, fn group ->
        "'#{group.name}', #{group_json_expr(group)}"
      end)

    {var_pairs, _} =
      Enum.map_reduce(var_fields, nil, fn {name, type, opts}, prev_offset_expr ->
        offset_expr =
          case prev_offset_expr do
            nil -> var_data_start_expr(groups, block_length)
            prev -> "#{prev} + 2 + gridcodec.read_u16(data, #{prev})"
          end

        value_expr = sql_json_var_value_expr(name, type, offset_expr, opts)
        {"'#{name}', #{value_expr}", offset_expr}
      end)

    all_pairs = Enum.join(fixed_pairs ++ group_pairs ++ var_pairs, ",\n    ")

    """
    CREATE OR REPLACE FUNCTION gridcodec.decode_#{fn_name}_json(data bytea)
    RETURNS jsonb AS $$
    SELECT jsonb_build_object(
      #{all_pairs}
    );
    $$ LANGUAGE sql IMMUTABLE STRICT;

    """
  end

  defp sql_json_value_expr(_name, type, type_mod, offset) do
    sql_fast_value_expr(type, type_mod, offset) || "NULL"
  end

  defp sql_json_value_expr(_name, type, type_mod, offset, opts) do
    sql_fast_value_expr(type, type_mod, offset, opts) || "NULL"
  end

  defp sql_json_var_value_expr(_name, type, offset_expr, opts) do
    expression =
      case type do
        t when t in [:string, :string16] ->
          "gridcodec.read_string16(data, (#{offset_expr})::int)"

        _ ->
          "NULL"
      end

    guard_since(expression, opts)
  end

  defp decimal_domain_type?(:decimal), do: true
  defp decimal_domain_type?(:positive_decimal), do: true
  defp decimal_domain_type?({type, _opts}), do: type in [:decimal, :positive_decimal]
  defp decimal_domain_type?(_type), do: false

  defp decimal_sql_value_expr(type, type_mod, data, offset) do
    if type_mod in [GridCodec.Types.Decimal, GridCodec.Types.PositiveDecimal] do
      "gridcodec.read_decimal(#{data}, #{sql_offset(offset)})"
    else
      scale = decimal_scale(type)
      read = integer_wire_read_expr!(type_mod, data, offset)
      null_value = type_mod.null_value()

      "CASE WHEN #{read} = #{null_value} THEN NULL " <>
        "ELSE #{read} * power(10::numeric, #{-scale}) END"
    end
  end

  defp decimal_scale({_type, opts}), do: Keyword.get(opts, :scale, 0)
  defp decimal_scale(_type), do: 0

  defp integer_wire_read_expr!(type_mod, data, offset) do
    function =
      case type_mod do
        GridCodec.Types.U8 -> "read_u8"
        GridCodec.Types.I8 -> "read_i8"
        GridCodec.Types.U16 -> "read_u16"
        GridCodec.Types.I16 -> "read_i16"
        GridCodec.Types.U32 -> "read_u32"
        GridCodec.Types.I32 -> "read_i32"
        GridCodec.Types.U64 -> "read_u64"
        GridCodec.Types.I64 -> "read_i64"
        _ -> raise ArgumentError, "unsupported SQL decimal wire type: #{inspect(type_mod)}"
      end

    "gridcodec.#{function}(#{data}, #{sql_offset(offset)})"
  end

  # ============================================================================
  # Private: Type → SQL Mapping
  # ============================================================================

  defp generate_field_reader_function(fn_name, field, type, type_mod, offset, opts) do
    reader_name = "read_#{fn_name}_#{sql_function_part(field)}"
    return_type = sql_column_type(type)

    value_expr =
      case sql_fast_value_expr(type, type_mod, offset, opts) do
        nil ->
          raise ArgumentError,
                "cannot generate PostgreSQL field reader for #{inspect(field)} type #{inspect(type)}"

        expression ->
          expression
      end

    """
    CREATE OR REPLACE FUNCTION gridcodec.#{reader_name}(data bytea)
    RETURNS #{return_type} AS $$
      SELECT #{value_expr};
    $$ LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE;

    """
  end

  defp sql_fast_value_expr(type, type_mod, offset) do
    sql_fast_value_expr(type, type_mod, offset, [], "data")
  end

  defp sql_fast_value_expr(type, type_mod, offset, opts) do
    sql_fast_value_expr(type, type_mod, offset, opts, "data")
  end

  defp sql_fast_value_expr(type, type_mod, offset, opts, data) do
    expression =
      cond do
        char_array_type?(type_mod) ->
          length = type_mod.__char_array_meta__().length
          "gridcodec.read_char_array(#{data}, #{sql_offset(offset)}, #{length})"

        enum_type?(type) ->
          enum_inline_case_expr(type, data, offset)

        type == :u8 ->
          "NULLIF(get_byte(#{data}, #{sql_offset(offset)}), 255)::smallint"

        type == :i8 ->
          "NULLIF(gridcodec.read_i8(#{data}, #{sql_offset(offset)}), -128)"

        type == :u16 ->
          "NULLIF(gridcodec.read_u16(#{data}, #{sql_offset(offset)}), 65535)"

        type == :i16 ->
          "NULLIF(gridcodec.read_i16(#{data}, #{sql_offset(offset)}), -32768)"

        type == :u32 ->
          "NULLIF(gridcodec.read_u32(#{data}, #{sql_offset(offset)}), 4294967295)"

        type == :i32 ->
          "NULLIF(gridcodec.read_i32(#{data}, #{sql_offset(offset)}), -2147483648)"

        type == :u64 ->
          "NULLIF(gridcodec.read_u64(#{data}, #{sql_offset(offset)}), 18446744073709551615::numeric)"

        type == :i64 ->
          "NULLIF(gridcodec.read_i64_bigint(#{data}, #{sql_offset(offset)}), -9223372036854775808)"

        type in [:uuid, :uuid_string] ->
          "gridcodec.read_uuid_nullable(#{data}, #{sql_offset(offset)})"

        prefixed_id_type?(type) ->
          prefix = prefixed_id_prefix(type)

          "CASE WHEN get_byte(#{data}, #{sql_offset(offset)}) = 0" <>
            " AND substring(#{data} FROM #{sql_offset_plus(offset, 2)} FOR 16) = '\\x00000000000000000000000000000000'::bytea" <>
            " THEN NULL" <>
            " ELSE #{sql_literal(prefix)} || encode(substring(#{data} FROM #{sql_offset_plus(offset, 2)} FOR 16), 'hex')::uuid::text" <>
            " END"

        type == :bool ->
          "gridcodec.read_bool(#{data}, #{sql_offset(offset)})"

        decimal_domain_type?(type) ->
          decimal_sql_value_expr(type, type_mod, data, offset)

        type in [:timestamp_us, :datetime_us] ->
          "gridcodec.read_timestamp_us(#{data}, #{sql_offset(offset)})"

        true ->
          nil
      end

    guard_since(expression, opts, data)
  end

  defp guard_since(expression, opts) do
    guard_since(expression, opts, "data")
  end

  defp guard_since(nil, _opts, _data), do: nil

  defp guard_since(expression, opts, data) do
    case Keyword.get(opts, :since) do
      since when is_integer(since) and since > 1 ->
        "CASE WHEN gridcodec.read_u16(#{data}, 6) < #{since} THEN NULL ELSE #{expression} END"

      _since ->
        expression
    end
  end

  defp sql_column_type(type) when is_atom(type) do
    cond do
      type in [:u8, :i8] -> "smallint"
      type in [:u16, :i16] -> "integer"
      type in [:u32, :i32] -> "bigint"
      type == :u64 -> "numeric"
      type == :i64 -> "bigint"
      type in [:f32, :f64] -> "double precision"
      type == :uuid -> "uuid"
      type == :uuid_string -> "uuid"
      type == :bool -> "boolean"
      type == :decimal -> "numeric"
      type in [:timestamp_us, :timestamp_ns, :datetime_us, :datetime_ns] -> "timestamptz"
      type in [:string, :string8, :string16, :string32] -> "text"
      enum_type?(type) -> "text"
      prefixed_id_type?(type) -> "text"
      true -> "text"
    end
  end

  defp sql_column_type({:decimal, _opts}), do: "numeric"
  defp sql_column_type({:positive_decimal, _opts}), do: "numeric"
  defp sql_column_type({_type, _opts}), do: "text"

  defp sql_read_expr(name, type, type_mod, offset, opts) do
    case sql_fast_value_expr(type, type_mod, offset, opts) do
      nil -> "'unsupported:#{inspect(type)}'::text AS \"#{name}\""
      expression -> "#{expression} AS \"#{name}\""
    end
  end

  defp sql_read_var_expr(name, type, offset_expr, opts) do
    expression =
      case type do
        t when t in [:string, :string16] ->
          "gridcodec.read_string16(data, (#{offset_expr})::int)"

        :string8 ->
          "'unsupported:string8'::text"

        _ ->
          "'unsupported:#{type}'::text"
      end

    "#{guard_since(expression, opts)} AS \"#{name}\""
  end
end
