defmodule Mix.Tasks.GridCodec.Gen.PrefixedId do
  @shortdoc "Generate a PrefixedId type module with visible source code"
  @moduledoc """
  Generates a PrefixedId type module with all public helpers written as
  visible, navigable source code — including doctests for test coverage.

  ## Usage

      mix grid_codec.gen.prefixed_id MyApp.Types.UserId --prefix user --tag 1
      mix grid_codec.gen.prefixed_id MyApp.Types.OrderId --prefix ord --tag 16

  ## Options

  - `--prefix` — string prefix without trailing dash (e.g., `user`) **(required)**
  - `--tag` — u8 integer 1..254 **(required)**; 0x00 is reserved for null
  - `--schema` — schema name for `.grid` export placement (e.g., `events`)
  - `--force` — overwrite existing files without prompting
  - `--no-test` — skip generating the companion test file

  ## What This Generates

  **Source module** (`lib/…`):

  - `@moduledoc`, `@type t()`, `@typedoc` — visible in source and ExDoc
  - `generate/0`, `from_uuid/1`, `to_uuid/1`, `valid?/1`, `prefix/0`, `tag/0` — with `@doc`, `@spec`, and doctests
  - `use GridCodec.Types.PrefixedId` — slim macro that injects only the compile-time
    `@impl GridCodec.Type` callbacks (not visible in source, but not needed for docs)

  **Test file** (`test/…`):

  - `doctest MyApp.Types.UserId` — exercises every doctest in the module

  ## Customizing Generated Modules

  Generated files are meant to be edited. A common pattern is adding a
  deterministic constructor for domain keys using `UUID.generate_v5/2`:

      @spec new(String.t(), integer(), pos_integer()) :: t()
      def new(market_id, window_start, seq) do
        raw = UUID.generate_v5(:url, "\#{market_id}:\#{window_start}:\#{seq}")
        prefix() <> UUIDString.format_uuid(raw)
      end
  """

  use Mix.Task

  @switches [prefix: :string, tag: :integer, schema: :string, force: :boolean, test: :boolean]

  @impl Mix.Task
  def run(args) do
    {opts, argv, _} = OptionParser.parse(args, switches: @switches)

    module_name =
      case argv do
        [name | _] -> name
        [] -> Mix.raise("Usage: mix grid_codec.gen.prefixed_id MODULE --prefix PREFIX --tag TAG")
      end

    prefix = opts[:prefix] || Mix.raise("--prefix is required")
    tag = opts[:tag] || Mix.raise("--tag is required")
    force = Keyword.get(opts, :force, false)
    gen_test = Keyword.get(opts, :test, true)

    unless is_integer(tag) and tag >= 1 and tag <= 254 do
      Mix.raise("--tag must be an integer 1..254 (0 is reserved for null)")
    end

    unless String.length(prefix) > 0 do
      Mix.raise("--prefix must be a non-empty string")
    end

    schema = opts[:schema]
    full_prefix = prefix <> "-"
    tag_hex = format_tag_hex(tag)

    assigns = [
      module_name: module_name,
      prefix: prefix,
      full_prefix: full_prefix,
      tag_hex: tag_hex,
      schema: schema
    ]

    source_path = module_to_path(module_name, "lib")
    write_file(source_path, generate_source(assigns), force)

    if gen_test do
      test_path = module_to_path(module_name, "test") |> String.replace(".ex", "_test.exs")
      test_module = module_name <> "Test"
      write_file(test_path, generate_test(module_name, test_module), force)
    end

    Mix.shell().info("""

    Generated #{module_name}

    Use it in a codec:

        defcodec do
          field :id, #{module_name}
        end
    """)
  end

  defp use_schema_opt(nil), do: ""
  defp use_schema_opt(schema), do: ~s(, schema: "#{schema}")

  defp format_tag_hex(tag) do
    "0x" <> (Integer.to_string(tag, 16) |> String.pad_leading(2, "0") |> String.upcase())
  end

  defp module_to_path(module_name, root) do
    path =
      module_name
      |> String.replace(~r/^Elixir\./, "")
      |> Macro.underscore()

    Path.join(root, path <> ".ex")
  end

  defp write_file(path, contents, force) do
    if File.exists?(path) and not force do
      Mix.raise(
        "File #{path} already exists. Use --force to overwrite, " <>
          "or delete it first."
      )
    end

    path |> Path.dirname() |> File.mkdir_p!()
    File.write!(path, contents)
    Mix.shell().info([:green, "* creating ", :reset, path])
    format_file(path)
  end

  defp format_file(path) do
    Mix.Tasks.Format.run([path])
  rescue
    _ -> :ok
  end

  # ================================================================
  # Source generation
  # ================================================================

  defp grid_codec_version do
    case :application.get_key(:grid_codec, :vsn) do
      {:ok, vsn} -> to_string(vsn)
      _ -> "dev"
    end
  end

  defp generate_source(assigns) do
    mod = assigns[:module_name]
    prefix = assigns[:prefix]
    fp = assigns[:full_prefix]
    tag_hex = assigns[:tag_hex]
    schema = assigns[:schema]
    prefix_len = byte_size(fp)
    version = grid_codec_version()

    ~s"""
    # Generated by mix grid_codec.gen.prefixed_id (grid_codec v#{version})
    # This file is meant to be edited. Regenerate with --force to reset.
    defmodule #{mod} do
      @moduledoc \"""
      GridCodec prefixed ID type: `#{fp}<uuid>` (tag `#{tag_hex}`).

      ## Prefixed ID

      Wire format: 17 bytes (u8 tag + 16-byte UUID). Prefix: `#{fp}` | Tag: `#{tag_hex}`

      | Function | Description |
      |----------|-------------|
      | `generate/0` | Create a new prefixed ID with a random UUIDv4 |
      | `from_uuid/1` | Prepend the prefix to a plain UUID string |
      | `to_uuid/1` | Strip the prefix, returning the plain UUID |
      | `valid?/1` | Check if a value is a valid prefixed ID for this type |
      | `prefix/0` | Returns the string prefix (including trailing dash) |
      | `tag/0` | Returns the wire tag byte |
      \"""

      use GridCodec.Types.PrefixedId, prefix: "#{prefix}", tag: #{tag_hex}#{use_schema_opt(schema)}

      alias GridCodec.Types.PrefixedId
      alias GridCodec.Types.UUID
      alias GridCodec.Types.UUIDString

      @typedoc "A prefixed ID string of the form `#{fp}<uuid>`."
      @type t() :: String.t()

      @doc \"""
      Generates a new prefixed ID with a random UUIDv4.

          iex> id = #{mod}.generate()
          iex> String.starts_with?(id, "#{fp}")
          true
          iex> String.length(id)
          #{byte_size(fp) + 36}
          iex> #{mod}.valid?(id)
          true
      \"""
      @spec generate() :: t()
      def generate do
        raw = UUID.generate_v4()
        "#{fp}" <> UUIDString.format_uuid(raw)
      end

      @doc \"""
      Prepends the prefix to a plain UUID string.

          iex> #{mod}.from_uuid("550e8400-e29b-41d4-a716-446655440000")
          "#{fp}550e8400-e29b-41d4-a716-446655440000"
      \"""
      @spec from_uuid(String.t()) :: t()
      def from_uuid(uuid_str) when is_binary(uuid_str), do: "#{fp}" <> uuid_str

      @doc \"""
      Strips the prefix, returning the plain UUID string.

          iex> #{mod}.to_uuid("#{fp}550e8400-e29b-41d4-a716-446655440000")
          "550e8400-e29b-41d4-a716-446655440000"
      \"""
      @spec to_uuid(t()) :: String.t()
      def to_uuid(<<prefix::binary-size(#{prefix_len}), uuid_str::binary>>)
          when prefix == "#{fp}",
          do: uuid_str

      @doc \"""
      Returns `true` if the value is a valid prefixed ID for this type.

          iex> #{mod}.valid?("#{fp}550e8400-e29b-41d4-a716-446655440000")
          true
          iex> #{mod}.valid?("wrong-550e8400-e29b-41d4-a716-446655440000")
          false
          iex> #{mod}.valid?(nil)
          false
      \"""
      @spec valid?(t() | term()) :: boolean()
      def valid?(<<prefix::binary-size(#{prefix_len}), uuid_str::binary-size(36)>>)
          when prefix == "#{fp}" do
        PrefixedId.valid_uuid_string?(uuid_str)
      end

      def valid?(_), do: false

      @doc \"""
      Returns the string prefix (including trailing dash).

          iex> #{mod}.prefix()
          "#{fp}"
      \"""
      @spec prefix() :: String.t()
      def prefix, do: "#{fp}"

      @doc \"""
      Returns the wire tag byte.

          iex> #{mod}.tag()
          #{tag_hex}
      \"""
      @spec tag() :: 0..254
      def tag, do: #{tag_hex}
    end
    """
  end

  # ================================================================
  # Test file generation
  # ================================================================

  defp generate_test(module_name, test_module) do
    version = grid_codec_version()

    ~s"""
    # Generated by mix grid_codec.gen.prefixed_id (grid_codec v#{version})
    defmodule #{test_module} do
      use ExUnit.Case, async: true

      doctest #{module_name}
    end
    """
  end
end
