# Generated by mix grid_codec.gen.prefixed_id (grid_codec v0.30.0)
# This file is meant to be edited. Regenerate with --force to reset.
defmodule ExampleApp.Types.OrderId do
  @moduledoc """
  GridCodec prefixed ID type: `ord-<uuid>` (tag `0x01`).

  ## Prefixed ID

  Wire format: 17 bytes (u8 tag + 16-byte UUID). Prefix: `ord-` | Tag: `0x01`

  | Function | Description |
  |----------|-------------|
  | `generate/0` | Create a new prefixed ID with a random UUIDv4 |
  | `from_uuid/1` | Prepend the prefix to a plain UUID string |
  | `to_uuid/1` | Strip the prefix, returning the plain UUID |
  | `valid?/1` | Check if a value is a valid prefixed ID for this type |
  | `prefix/0` | Returns the string prefix (including trailing dash) |
  | `tag/0` | Returns the wire tag byte |
  """

  use GridCodec.Types.PrefixedId, prefix: "ord", tag: 0x01

  alias GridCodec.Types.PrefixedId
  alias GridCodec.Types.UUID
  alias GridCodec.Types.UUIDString

  @typedoc "A prefixed ID string of the form `ord-<uuid>`."
  @type t() :: String.t()

  @doc """
  Generates a new prefixed ID with a random UUIDv4.

      iex> id = ExampleApp.Types.OrderId.generate()
      iex> String.starts_with?(id, "ord-")
      true
      iex> String.length(id)
      40
      iex> ExampleApp.Types.OrderId.valid?(id)
      true
  """
  @spec generate() :: t()
  def generate do
    raw = UUID.generate_v4()
    "ord-" <> UUIDString.format_uuid(raw)
  end

  @doc """
  Prepends the prefix to a plain UUID string.

      iex> ExampleApp.Types.OrderId.from_uuid("550e8400-e29b-41d4-a716-446655440000")
      "ord-550e8400-e29b-41d4-a716-446655440000"
  """
  @spec from_uuid(String.t()) :: t()
  def from_uuid(uuid_str) when is_binary(uuid_str), do: "ord-" <> uuid_str

  @doc """
  Strips the prefix, returning the plain UUID string.

      iex> ExampleApp.Types.OrderId.to_uuid("ord-550e8400-e29b-41d4-a716-446655440000")
      "550e8400-e29b-41d4-a716-446655440000"
  """
  @spec to_uuid(t()) :: String.t()
  def to_uuid(<<prefix::binary-size(4), uuid_str::binary>>)
      when prefix == "ord-",
      do: uuid_str

  @doc """
  Returns `true` if the value is a valid prefixed ID for this type.

      iex> ExampleApp.Types.OrderId.valid?("ord-550e8400-e29b-41d4-a716-446655440000")
      true
      iex> ExampleApp.Types.OrderId.valid?("wrong-550e8400-e29b-41d4-a716-446655440000")
      false
      iex> ExampleApp.Types.OrderId.valid?(nil)
      false
  """
  @spec valid?(t() | term()) :: boolean()
  def valid?(<<prefix::binary-size(4), uuid_str::binary-size(36)>>)
      when prefix == "ord-" do
    PrefixedId.valid_uuid_string?(uuid_str)
  end

  def valid?(_), do: false

  @doc """
  Returns the string prefix (including trailing dash).

      iex> ExampleApp.Types.OrderId.prefix()
      "ord-"
  """
  @spec prefix() :: String.t()
  def prefix, do: "ord-"

  @doc """
  Returns the wire tag byte.

      iex> ExampleApp.Types.OrderId.tag()
      0x01
  """
  @spec tag() :: 0..254
  def tag, do: 0x01
end
