defmodule GridCodec.Schema.Formatter do
  @moduledoc """
  Converts runtime GridCodec schema metadata into `.grid` file content.

  Takes compiled codec modules' `__schema__/0` data, detects enum types
  referenced by fields, and produces a formatted `.grid` string.
  """

  @type codec_entry :: {module(), map()}

  @encoding_to_grid %{u8: "u8", u16: "u16", u32: "u32"}

  @doc """
  Formats a list of codec entries into a `.grid` file string.

  Expects `codecs` as `[{module, schema_map}]` all sharing the same schema_id.
  The `schema_name` is used for the top-level `schema` block.
  """
  @spec format(String.t(), integer(), integer(), [codec_entry()]) :: String.t()
  def format(schema_name, schema_id, schema_version, codecs) do
    enums = detect_enums(codecs)
    type_aliases = build_type_aliases(codecs, enums)

    lines = [
      "# Auto-generated by mix grid_codec.export",
      "# Do not edit — regenerate with: mix grid_codec.export",
      "",
      format_schema_block(schema_name, schema_id, schema_version),
      ""
    ]

    enum_lines =
      enums
      |> Enum.sort_by(fn {_mod, info} -> info.short_name end)
      |> Enum.flat_map(fn {_mod, info} ->
        [format_enum_block(info), ""]
      end)

    struct_lines =
      codecs
      |> Enum.sort_by(fn {_mod, schema} -> schema.template_id end)
      |> Enum.flat_map(fn {_mod, schema} ->
        [format_struct_block(schema, type_aliases), ""]
      end)

    (lines ++ enum_lines ++ struct_lines)
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  # ============================================================================
  # Schema block
  # ============================================================================

  defp format_schema_block(name, id, version) do
    "schema #{name} {\n  id: #{id}\n  version: #{version}\n}"
  end

  # ============================================================================
  # Enum detection and formatting
  # ============================================================================

  @doc false
  def detect_enums(codecs) do
    codecs
    |> Enum.flat_map(fn {_mod, schema} ->
      Enum.map(schema.fields, fn {_name, type_spec, _opts} ->
        normalize_type_module(type_spec)
      end)
    end)
    |> Enum.uniq()
    |> Enum.filter(&enum_module?/1)
    |> Enum.map(fn mod ->
      {mod,
       %{
         module: mod,
         short_name: short_module_name(mod),
         encoding: mod.encoding(),
         values: mod.values()
       }}
    end)
    |> Map.new()
  end

  defp enum_module?(mod) when is_atom(mod) do
    Code.ensure_loaded?(mod) and
      function_exported?(mod, :values, 0) and
      function_exported?(mod, :encoding, 0)
  end

  defp enum_module?(_), do: false

  defp format_enum_block(info) do
    encoding_str = Map.get(@encoding_to_grid, info.encoding, Atom.to_string(info.encoding))
    values = Enum.map_join(info.values, "\n", fn {name, int} -> "  #{name} = #{int}" end)
    "enum #{info.short_name} : #{encoding_str} {\n#{values}\n}"
  end

  # ============================================================================
  # Struct formatting
  # ============================================================================

  defp format_struct_block(schema, type_aliases) do
    name = struct_name(schema)
    header = format_struct_header(name, schema)

    field_lines =
      schema.fields
      |> Enum.map(fn {fname, type_spec, opts} ->
        type_str = format_type(type_spec, type_aliases)
        field_name = format_field_name(fname, opts)
        opts_str = format_field_opts(opts)

        if opts_str == "" do
          "  #{field_name}: #{type_str}"
        else
          "  #{field_name}: #{type_str}, #{opts_str}"
        end
      end)

    original_groups =
      (schema.groups || [])
      |> Enum.map(fn {gname, _block, _opts} -> gname end)

    group_lines =
      original_groups
      |> Enum.flat_map(fn gname ->
        gfields = Map.get(schema.group_fields || %{}, gname, [])

        if gfields == [] do
          []
        else
          field_strs =
            Enum.map(gfields, fn {fname, type_atom} -> "    #{fname}: #{type_atom}" end)

          ["", "  group #{gname} {"] ++ field_strs ++ ["  }"]
        end
      end)

    batch_lines =
      (schema.batches || [])
      |> Enum.flat_map(fn {bname, any_of_modules, strategy} ->
        type_names =
          Enum.map_join(any_of_modules, ", ", fn mod -> short_module_name(mod) end)

        [
          "",
          "  batch #{bname} {",
          "    any_of: [#{type_names}]",
          "    strategy: #{strategy}",
          "  }"
        ]
      end)

    body = Enum.join(field_lines ++ group_lines ++ batch_lines, "\n")
    "#{header} {\n#{body}\n}"
  end

  # ============================================================================
  # Type resolution
  # ============================================================================

  defp build_type_aliases(codecs, enums) do
    enum_aliases = Map.new(enums, fn {mod, info} -> {mod, info.short_name} end)

    codec_aliases =
      codecs
      |> Map.new(fn {mod, schema} -> {mod, struct_name(schema)} end)

    Map.merge(enum_aliases, codec_aliases)
  end

  defp format_struct_header(name, schema) do
    attrs = ["template_id: #{schema.template_id}"]

    attrs =
      if schema.version && schema.version != 1 do
        attrs ++ ["version: #{schema.version}"]
      else
        attrs
      end

    "struct #{name} (#{Enum.join(attrs, ", ")})"
  end

  defp format_field_name(fname, _opts) do
    "#{fname}"
  end

  @field_opt_order [:wire_format, :since, :presence, :default, :value]

  defp format_field_opts(opts) do
    parts =
      Enum.flat_map(@field_opt_order, fn key ->
        val = Keyword.get(opts, key)

        cond do
          is_nil(val) -> []
          key == :presence and val == :optional -> []
          key == :default -> ["default: #{format_opt_value(val)}"]
          key == :value -> ["value: #{format_opt_value(val)}"]
          true -> ["#{key}: #{val}"]
        end
      end)

    Enum.join(parts, ", ")
  end

  defp format_opt_value(val) when is_binary(val), do: ~s("#{val}")
  defp format_opt_value(val), do: "#{val}"

  defp format_type(type_spec, type_aliases) do
    case normalize_type_spec(type_spec) do
      {base_type, []} ->
        resolve_type_name(base_type, type_aliases)

      {base_type, type_opts} ->
        base = resolve_type_name(base_type, type_aliases)
        params = Enum.map_join(type_opts, ", ", fn {k, v} -> "#{k}: #{v}" end)
        "#{base}(#{params})"
    end
  end

  defp resolve_type_name(type, type_aliases) do
    case Map.get(type_aliases, type) do
      nil -> Atom.to_string(type)
      name -> name
    end
  end

  defp normalize_type_spec({type, opts}) when is_atom(type) and is_list(opts), do: {type, opts}
  defp normalize_type_spec(type) when is_atom(type), do: {type, []}

  defp normalize_type_module({type, _opts}) when is_atom(type), do: type
  defp normalize_type_module(type) when is_atom(type), do: type

  defp struct_name(schema) do
    case schema.type do
      name when is_binary(name) ->
        name |> String.split(".") |> List.last()

      _ ->
        "Unknown"
    end
  end

  defp short_module_name(mod) when is_atom(mod) do
    mod |> Module.split() |> List.last()
  end
end
