defmodule GridCodec.Schema.Formatter do
  @moduledoc """
  Converts runtime GridCodec schema metadata into `.grid` file content.

  Takes compiled codec modules' `__schema__/0` data, detects enum types
  referenced by fields, and produces formatted `.grid` strings.

  ## Output Modes

  - `format/5` — single combined file with schema block + all definitions inline
  - `format_master/5` — master file with schema block + `import` directives
  - `format_struct_file/3` — standalone struct file (with optional type imports)
  - `format_enum_file/2` — standalone enum file

  All functions accept an `opts` keyword list with:
  - `:syntax` — target `.grid` syntax version (defaults to `current_syntax/0`)
  """

  @type codec_entry :: {module(), map()}

  @current_syntax 1
  @encoding_to_grid %{u8: "u8", u16: "u16", u32: "u32"}

  @comment "# Auto-generated by mix grid_codec.export\n# Do not edit — regenerate with: mix grid_codec.export"

  @doc "Returns the latest `.grid` syntax version the formatter supports."
  @spec current_syntax() :: pos_integer()
  def current_syntax, do: @current_syntax

  defp file_header(opts) do
    syntax = Keyword.get(opts, :syntax, @current_syntax)
    @comment <> "\n\n@syntax #{syntax}"
  end

  @doc """
  Formats a list of codec entries into a single combined `.grid` file string.

  Expects `codecs` as `[{module, schema_map}]` all sharing the same schema_id.
  The `schema_name` is used for the top-level `schema` block.
  Structs are sorted alphabetically by name.
  """
  @spec format(String.t(), integer(), integer(), [codec_entry()], keyword()) :: String.t()
  def format(schema_name, schema_id, schema_version, codecs, opts \\ []) do
    enums = detect_enums(codecs)
    type_aliases = build_type_aliases(codecs, enums)

    lines = [
      file_header(opts),
      "",
      format_schema_block(schema_name, schema_id, schema_version),
      ""
    ]

    enum_lines =
      enums
      |> Enum.sort_by(fn {_mod, info} -> info.short_name end)
      |> Enum.flat_map(fn {_mod, info} ->
        [format_enum_block(info), ""]
      end)

    struct_lines =
      codecs
      |> Enum.sort_by(fn {_mod, schema} -> struct_name(schema) end)
      |> Enum.flat_map(fn {_mod, schema} ->
        [format_struct_block(schema, type_aliases), ""]
      end)

    (lines ++ enum_lines ++ struct_lines)
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  @doc """
  Formats a master schema file with schema block and sorted import directives.

  Import paths are relative to the master file's directory.
  """
  @spec format_master(String.t(), integer(), integer(), [String.t()], keyword()) :: String.t()
  def format_master(schema_name, schema_id, schema_version, import_paths, opts \\ []) do
    import_lines =
      import_paths
      |> Enum.sort()
      |> Enum.map(fn path -> ~s(import "#{path}") end)

    lines =
      [
        file_header(opts),
        "",
        format_schema_block(schema_name, schema_id, schema_version),
        ""
      ] ++ import_lines

    lines
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  @doc """
  Formats a single struct as a standalone `.grid` file.

  `import_paths` is a list of relative paths to import (type dependencies).
  """
  @spec format_struct_file(map(), map(), keyword()) :: String.t()
  def format_struct_file(schema, type_aliases, opts \\ []) do
    import_paths = Keyword.get(opts, :imports, [])
    block = format_struct_block(schema, type_aliases)

    import_lines =
      import_paths
      |> Enum.sort()
      |> Enum.map(fn path -> ~s(import "#{path}") end)

    parts = [file_header(opts)] ++ import_section(import_lines) ++ ["", block]

    parts
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  @doc """
  Formats a single enum as a standalone `.grid` file.
  """
  @spec format_enum_file(map(), keyword()) :: String.t()
  def format_enum_file(enum_info, opts \\ []) do
    block = format_enum_block(enum_info)

    [file_header(opts), "", block]
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  @doc """
  Formats a single custom type (prefixed_id, char_array, bitset) as a standalone `.grid` file.
  """
  @spec format_custom_type_file(map(), keyword()) :: String.t()
  def format_custom_type_file(type_info, opts \\ []) do
    block = format_custom_type_block(type_info)

    [file_header(opts), "", block]
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp import_section([]), do: []
  defp import_section(lines), do: ["" | lines]

  # ============================================================================
  # Schema block
  # ============================================================================

  defp format_schema_block(name, id, version) do
    "schema #{name} {\n  id: #{id}\n  version: #{version}\n}"
  end

  # ============================================================================
  # Enum detection and formatting
  # ============================================================================

  @doc false
  def detect_enums(codecs) do
    codecs
    |> Enum.flat_map(fn {_mod, schema} ->
      Enum.map(schema.fields, fn {_name, type_spec, _opts} ->
        normalize_type_module(type_spec)
      end)
    end)
    |> Enum.uniq()
    |> Enum.filter(&enum_module?/1)
    |> Enum.map(&enum_info/1)
    |> Map.new()
  end

  @doc """
  Detects all enums referenced across multiple schema groups.

  Returns a map of `%{module => enum_info}` covering all schemas.
  """
  @spec detect_all_enums([[codec_entry()]]) :: map()
  def detect_all_enums(codec_groups) do
    codec_groups
    |> List.flatten()
    |> detect_enums()
  end

  @doc """
  Returns the set of enum modules referenced by a single struct's fields.
  """
  @spec referenced_enums(map(), map()) :: [module()]
  def referenced_enums(schema, all_enums) do
    schema.fields
    |> Enum.map(fn {_name, type_spec, _opts} -> normalize_type_module(type_spec) end)
    |> Enum.uniq()
    |> Enum.filter(fn mod -> Map.has_key?(all_enums, mod) end)
  end

  defp enum_info(mod) do
    {mod,
     %{
       module: mod,
       short_name: short_module_name(mod),
       encoding: mod.encoding(),
       values: mod.values()
     }}
  end

  defp enum_module?(mod) when is_atom(mod) do
    Code.ensure_loaded?(mod) and
      function_exported?(mod, :values, 0) and
      function_exported?(mod, :encoding, 0)
  end

  defp enum_module?(_), do: false

  defp format_enum_block(info) do
    encoding_str = Map.get(@encoding_to_grid, info.encoding, Atom.to_string(info.encoding))
    values = Enum.map_join(info.values, "\n", fn {name, int} -> "  #{name} = #{int}" end)
    "enum #{info.short_name} : #{encoding_str} {\n#{values}\n}"
  end

  # ============================================================================
  # Struct formatting
  # ============================================================================

  defp format_struct_block(schema, type_aliases) do
    name = struct_name(schema)
    header = format_struct_header(name, schema)

    field_lines =
      schema.fields
      |> Enum.map(fn {fname, type_spec, opts} ->
        type_str = format_type(type_spec, type_aliases)
        field_name = format_field_name(fname, opts)
        opts_str = format_field_opts(opts)

        if opts_str == "" do
          "  #{field_name}: #{type_str}"
        else
          "  #{field_name}: #{type_str}, #{opts_str}"
        end
      end)

    original_groups =
      (schema.groups || [])
      |> Enum.map(fn {gname, _block, _opts} -> gname end)

    group_lines =
      original_groups
      |> Enum.flat_map(fn gname ->
        gfields = Map.get(schema.group_fields || %{}, gname, [])

        if gfields == [] do
          []
        else
          field_strs =
            Enum.map(gfields, fn {fname, type_atom} -> "    #{fname}: #{type_atom}" end)

          ["", "  group #{gname} {"] ++ field_strs ++ ["  }"]
        end
      end)

    batch_lines =
      (schema.batches || [])
      |> Enum.flat_map(fn {bname, any_of_modules, strategy} ->
        type_names =
          Enum.map_join(any_of_modules, ", ", fn mod -> short_module_name(mod) end)

        [
          "",
          "  batch #{bname} {",
          "    any_of: [#{type_names}]",
          "    strategy: #{strategy}",
          "  }"
        ]
      end)

    body = Enum.join(field_lines ++ group_lines ++ batch_lines, "\n")
    "#{header} {\n#{body}\n}"
  end

  # ============================================================================
  # Type resolution
  # ============================================================================

  @doc """
  Builds a type alias map from codec entries and detected enums.

  Maps module atoms to their short display names for use in `.grid` output.
  """
  @spec build_type_aliases([codec_entry()], map()) :: map()
  def build_type_aliases(codecs, enums) do
    build_type_aliases(codecs, enums, %{})
  end

  @doc false
  def build_type_aliases(codecs, enums, custom_types) do
    enum_aliases = Map.new(enums, fn {mod, info} -> {mod, info.short_name} end)

    codec_aliases =
      codecs
      |> Map.new(fn {mod, schema} -> {mod, struct_name(schema)} end)

    custom_type_aliases = Map.new(custom_types, fn {mod, info} -> {mod, info.short_name} end)

    enum_aliases
    |> Map.merge(codec_aliases)
    |> Map.merge(custom_type_aliases)
  end

  @doc """
  Detects all custom types (PrefixedId, CharArray, Bitset) referenced by codec fields.
  """
  @spec detect_custom_types([codec_entry()]) :: map()
  def detect_custom_types(codecs) do
    codecs
    |> Enum.flat_map(fn {_mod, schema} ->
      Enum.map(schema.fields, fn {_name, type_spec, _opts} ->
        normalize_type_module(type_spec)
      end)
    end)
    |> Enum.uniq()
    |> Enum.filter(&custom_type_module?/1)
    |> Enum.map(&custom_type_info/1)
    |> Map.new()
  end

  @doc """
  Detects all custom types across multiple schema groups.
  """
  @spec detect_all_custom_types([[codec_entry()]]) :: map()
  def detect_all_custom_types(codec_groups) do
    codec_groups
    |> List.flatten()
    |> detect_custom_types()
  end

  @doc """
  Returns the set of custom type modules referenced by a single struct's fields.
  """
  @spec referenced_custom_types(map(), map()) :: [module()]
  def referenced_custom_types(schema, all_custom_types) do
    schema.fields
    |> Enum.map(fn {_name, type_spec, _opts} -> normalize_type_module(type_spec) end)
    |> Enum.uniq()
    |> Enum.filter(fn mod -> Map.has_key?(all_custom_types, mod) end)
  end

  defp custom_type_module?(mod) when is_atom(mod) do
    Code.ensure_loaded?(mod) and
      (function_exported?(mod, :__prefixed_id_meta__, 0) or
         function_exported?(mod, :__char_array_meta__, 0) or
         function_exported?(mod, :__bitset_meta__, 0))
  end

  defp custom_type_module?(_), do: false

  defp custom_type_info(mod) do
    cond do
      function_exported?(mod, :__prefixed_id_meta__, 0) ->
        meta = mod.__prefixed_id_meta__()

        {mod,
         %{
           module: mod,
           short_name: short_module_name(mod),
           kind: :prefixed_id,
           params: meta
         }}

      function_exported?(mod, :__char_array_meta__, 0) ->
        meta = mod.__char_array_meta__()

        {mod,
         %{
           module: mod,
           short_name: short_module_name(mod),
           kind: :char_array,
           params: meta
         }}

      function_exported?(mod, :__bitset_meta__, 0) ->
        meta = mod.__bitset_meta__()

        {mod,
         %{
           module: mod,
           short_name: short_module_name(mod),
           kind: :bitset,
           params: meta
         }}
    end
  end

  defp format_custom_type_block(%{kind: :prefixed_id, short_name: name, params: params}) do
    "prefixed_id #{name} {\n  prefix: \"#{params.prefix}\"\n  tag: #{params.tag}\n}"
  end

  defp format_custom_type_block(%{kind: :char_array, short_name: name, params: params}) do
    "char_array #{name} {\n  length: #{params.length}\n}"
  end

  defp format_custom_type_block(%{kind: :bitset, short_name: name, params: params}) do
    encoding_str = Map.get(@encoding_to_grid, params.size, Atom.to_string(params.size))
    values = Enum.map_join(params.flags, "\n", fn {fname, bit} -> "  #{fname} = #{bit}" end)
    "bitset #{name} : #{encoding_str} {\n#{values}\n}"
  end

  defp format_struct_header(name, schema) do
    attrs = ["template_id: #{schema.template_id}"]

    attrs =
      if schema.version && schema.version != 1 do
        attrs ++ ["version: #{schema.version}"]
      else
        attrs
      end

    "struct #{name} (#{Enum.join(attrs, ", ")})"
  end

  defp format_field_name(fname, _opts) do
    "#{fname}"
  end

  @field_opt_order [:wire_format, :since, :presence, :default, :value]

  defp format_field_opts(opts) do
    parts =
      Enum.flat_map(@field_opt_order, fn key ->
        val = Keyword.get(opts, key)

        cond do
          is_nil(val) -> []
          key == :presence and val == :optional -> []
          key == :default -> ["default: #{format_opt_value(val)}"]
          key == :value -> ["value: #{format_opt_value(val)}"]
          true -> ["#{key}: #{val}"]
        end
      end)

    Enum.join(parts, ", ")
  end

  defp format_opt_value(val) when is_binary(val), do: ~s("#{val}")
  defp format_opt_value(val), do: "#{val}"

  defp format_type(type_spec, type_aliases) do
    case normalize_type_spec(type_spec) do
      {base_type, []} ->
        resolve_type_name(base_type, type_aliases)

      {base_type, type_opts} ->
        base = resolve_type_name(base_type, type_aliases)
        params = Enum.map_join(type_opts, ", ", fn {k, v} -> "#{k}: #{v}" end)
        "#{base}(#{params})"
    end
  end

  defp resolve_type_name(type, type_aliases) do
    case Map.get(type_aliases, type) do
      nil -> Atom.to_string(type)
      name -> name
    end
  end

  defp normalize_type_spec({type, opts}) when is_atom(type) and is_list(opts), do: {type, opts}
  defp normalize_type_spec(type) when is_atom(type), do: {type, []}

  defp normalize_type_module({type, _opts}) when is_atom(type), do: type
  defp normalize_type_module(type) when is_atom(type), do: type

  @doc """
  Returns the short display name for a struct (last segment of `schema.type`).
  """
  def struct_name(schema) do
    case schema.type do
      name when is_binary(name) ->
        name |> String.split(".") |> List.last()

      _ ->
        "Unknown"
    end
  end

  defp short_module_name(mod) when is_atom(mod) do
    mod |> Module.split() |> List.last()
  end
end
